// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package bankrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAccountTransactions(ctx context.Context, accountID pgtype.UUID) (int64, error)
	CountCategoryChildren(ctx context.Context, parentID pgtype.UUID) (int64, error)
	CountCategoryTransactions(ctx context.Context, arg CountCategoryTransactionsParams) (int64, error)
	// bank module queries (SPEC-03). sqlc input only — regenerate with `make sqlc`;
	// never hand-edit the *.sql.go output. Money is integer minor units (bigint).
	// Every row is owner-scoped by user_id (P0.8), with one carve-out: category
	// READS span own + seed (user_id IS NULL); category MUTATIONS stay owner-scoped
	// (which is what makes seeds immutable/undeletable, P0.4).
	// ══ Accounts (P0.1) ═════════════════════════════════════════════════════
	CreateAccount(ctx context.Context, arg CreateAccountParams) (BankAccount, error)
	// ══ Categories (P0.4) ═══════════════════════════════════════════════════
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (BankCategory, error)
	// ══ Transactions (P0.2 / P0.3) ══════════════════════════════════════════
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (BankTransaction, error)
	// Owner-scoped. The service refuses when the account still has transactions
	// (409 bank/account-not-empty); the plain FK is the DB backstop.
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) (pgtype.UUID, error)
	DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error
	// Owner-scoped delete (seeds never match). Children are promoted to top level by
	// the ON DELETE SET NULL FK; budgets cascade. The service handles reassignment
	// of this category's own transactions in the same tx before calling this.
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (pgtype.UUID, error)
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (pgtype.UUID, error)
	// Remove every row of a transfer atomically (both legs, plus a fee row if any).
	DeleteTransferByID(ctx context.Context, arg DeleteTransferByIDParams) error
	GetAccount(ctx context.Context, arg GetAccountParams) (BankAccount, error)
	// Derived balance = opening_balance + Σcredits − Σdebits (never stored, P0.1).
	// ::bigint keeps sqlc from inferring int4 (VND balances overflow int32).
	GetAccountBalance(ctx context.Context, arg GetAccountBalanceParams) (int64, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (BankTransaction, error)
	// Own or seed (user_id IS NULL). Used for attach validation (P0.2) and GET; a
	// foreign category id resolves to no row → 404 (existence never leaks).
	GetVisibleCategory(ctx context.Context, arg GetVisibleCategoryParams) (BankCategory, error)
	// Every account with its current derived balance (dashboard P0.6 + list). Always
	// current — never month-scoped (§11 opening-balance rule).
	ListAccountBalances(ctx context.Context, userID pgtype.UUID) ([]ListAccountBalancesRow, error)
	// All of the caller's accounts (archived included; the service/handler hides
	// archived from pickers). Ordered active-first then name.
	ListAccounts(ctx context.Context, userID pgtype.UUID) ([]BankAccount, error)
	// Each budgeted category for the month with its amount, name, parent (id+name for
	// header synthesis), and spent = Σ expense debits in the month for the category
	// INCLUDING its direct children, excluding pure transfer legs (a leg has
	// category_id NULL so the category join already drops it; a P1.13 fee row keeps
	// its category and counts — reporting keys on leg-ness, not transfer_id).
	ListBudgetsForMonth(ctx context.Context, arg ListBudgetsForMonthParams) ([]ListBudgetsForMonthRow, error)
	// Own + seed, ordered so parents precede their children for tree assembly.
	ListCategories(ctx context.Context, userID pgtype.UUID) ([]BankCategory, error)
	// Keyset page, newest first (occurred_at DESC, id DESC). Optional account/month/
	// category filters (a NULL arg skips its clause). A NULL cursor starts at the top.
	ListTransactionsByUserCursor(ctx context.Context, arg ListTransactionsByUserCursorParams) ([]BankTransaction, error)
	// ══ Transfers (P0.3) ════════════════════════════════════════════════════
	// All rows sharing a transfer_id, owner-scoped (the pair, plus any P1.13 fee row).
	ListTransferLegs(ctx context.Context, arg ListTransferLegsParams) ([]BankTransaction, error)
	// ══ Dashboard (P0.6) ════════════════════════════════════════════════════
	// Month income/expense totals, excluding pure transfer legs (transfer_id set AND
	// category_id NULL) — NOT `WHERE transfer_id IS NULL`, which would wrongly drop a
	// P1.13 fee row. A fee row (both set) counts as an ordinary expense.
	MonthFlowTotals(ctx context.Context, arg MonthFlowTotalsParams) (MonthFlowTotalsRow, error)
	// Move this category's own transactions to the target (P0.4 delete ?reassign_to).
	ReassignCategoryTransactions(ctx context.Context, arg ReassignCategoryTransactionsParams) error
	// Dashboard: the 10 most recently ENTERED rows (created_at DESC — a future-dated
	// entry must not pin the list, P0.6).
	RecentTransactions(ctx context.Context, arg RecentTransactionsParams) ([]BankTransaction, error)
	// Partial update of {name, archived}. currency is immutable (P0.1) so it is not
	// updatable here. NULL arg leaves the column unchanged.
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (BankAccount, error)
	// Owner-scoped (seeds have user_id NULL so they never match → immutable, P0.4).
	// kind is immutable; only {name, parent_id} change. A NULL name leaves it; the
	// service passes parent_id explicitly (clearing to top-level is a real value).
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (BankCategory, error)
	// Owner-scoped partial update. The service blocks transfer legs (409) before
	// calling this, so it only ever edits ordinary rows.
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (BankTransaction, error)
	// ══ Budgets (P0.5) ══════════════════════════════════════════════════════
	// One amount per (category, month). amount > 0 (the §6 CHECK); sending 0/null is
	// a delete, handled by the service via DeleteBudget.
	UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (BankBudget, error)
}

var _ Querier = (*Queries)(nil)
