// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package peoplerepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Every user's people with a solar birthday — the daily scan iterates this.
	AllSolarBirthdays(ctx context.Context) ([]AllSolarBirthdaysRow, error)
	// people module queries (SPEC-08). sqlc input only — regenerate with `make sqlc`.
	// Owner-scoped. Birthday is month/day + optional year; the notices table is the
	// daily scan's outbox/dedup (P0.4).
	// ══ Persons ═════════════════════════════════════════════════════════════
	CreatePerson(ctx context.Context, arg CreatePersonParams) (PeoplePerson, error)
	// On a birthday edit/clear, drop current + future notices so a corrected date
	// can fire fresh this year (P0.2). Past years' history stays.
	DeleteFutureNotices(ctx context.Context, arg DeleteFutureNoticesParams) error
	DeletePerson(ctx context.Context, arg DeletePersonParams) (pgtype.UUID, error)
	GetPerson(ctx context.Context, arg GetPersonParams) (PeoplePerson, error)
	// ══ Birthday notices — outbox/dedup (P0.4) ══════════════════════════════
	// Reserve the (person, year, threshold) slot; a conflict means it already fired.
	InsertNotice(ctx context.Context, arg InsertNoticeParams) error
	ListPeople(ctx context.Context, arg ListPeopleParams) ([]PeoplePerson, error)
	// The caller's people that have a (solar) birthday — for the upcoming endpoint.
	ListSolarBirthdays(ctx context.Context, userID pgtype.UUID) ([]ListSolarBirthdaysRow, error)
	MarkNoticeEmitted(ctx context.Context, id pgtype.UUID) error
	// Notices written but not yet published (fresh + prior-failed) with their person.
	PendingNotices(ctx context.Context) ([]PendingNoticesRow, error)
	// Partial update. Birthday travels as a group: set_birthday rewrites all four
	// columns (to the given values, or NULL to clear). relationship/note clear via
	// their own set flags; display_name/contact use COALESCE (leave when NULL).
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (PeoplePerson, error)
}

var _ Querier = (*Queries)(nil)
