// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package musicrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// music module queries. sqlc input only. Owner-scoped mutations; published-or-
	// owner reads. Asset ids validated via mediaapi (no cross-module FK), reaped via
	// media:asset_deleted. tenant_id is filled by its column DEFAULT (RequireTenant
	// sets app.current_tenant) — never inserted here.
	CreateTrack(ctx context.Context, arg CreateTrackParams) (MusicTrack, error)
	DeleteTrack(ctx context.Context, id pgtype.UUID) error
	GetTrack(ctx context.Context, id pgtype.UUID) (MusicTrack, error)
	GetTrackOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	ListOwnTracks(ctx context.Context, arg ListOwnTracksParams) ([]MusicTrack, error)
	ListPublishedTracks(ctx context.Context, arg ListPublishedTracksParams) ([]MusicTrack, error)
	// ══ media:asset_deleted consumer ══════════════════════════════════════════
	// NullAudioByAsset also unpublishes: a published track with no audio is broken.
	NullAudioByAsset(ctx context.Context, audioAssetID pgtype.UUID) error
	NullTrackCoverByAsset(ctx context.Context, coverAssetID pgtype.UUID) error
	UpdateTrack(ctx context.Context, arg UpdateTrackParams) (MusicTrack, error)
	UpdateTrackStatus(ctx context.Context, arg UpdateTrackStatusParams) (MusicTrack, error)
}

var _ Querier = (*Queries)(nil)
