// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storyrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountStoryChapters(ctx context.Context, storyID pgtype.UUID) (int64, error)
	// story module queries. sqlc input only. Owner-scoped mutations; published-or-
	// owner reads. cover_asset_id validated via mediaapi (no FK), reaped via
	// media:asset_deleted. tenant_id filled by column DEFAULT (RequireTenant sets
	// app.current_tenant) — never inserted here.
	// ══ Stories ══════════════════════════════════════════════════════════════
	CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error)
	// ══ Chapters ═══════════════════════════════════════════════════════════════
	CreateStoryChapter(ctx context.Context, arg CreateStoryChapterParams) (StoryChapter, error)
	DeleteStory(ctx context.Context, id pgtype.UUID) error
	DeleteStoryChapter(ctx context.Context, id pgtype.UUID) error
	// EmptyChapters lists chapters with a blank body — the publish blocker.
	EmptyChapters(ctx context.Context, storyID pgtype.UUID) ([]EmptyChaptersRow, error)
	GetStory(ctx context.Context, id pgtype.UUID) (Story, error)
	GetStoryChapter(ctx context.Context, id pgtype.UUID) (StoryChapter, error)
	GetStoryOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetStoryOwnerByChapter(ctx context.Context, id pgtype.UUID) (GetStoryOwnerByChapterRow, error)
	ListOwnStories(ctx context.Context, arg ListOwnStoriesParams) ([]ListOwnStoriesRow, error)
	ListPublishedStories(ctx context.Context, arg ListPublishedStoriesParams) ([]ListPublishedStoriesRow, error)
	ListStoryChapters(ctx context.Context, storyID pgtype.UUID) ([]StoryChapter, error)
	NullStoryCoverByAsset(ctx context.Context, coverAssetID pgtype.UUID) error
	UpdateStory(ctx context.Context, arg UpdateStoryParams) (Story, error)
	UpdateStoryChapter(ctx context.Context, arg UpdateStoryChapterParams) (StoryChapter, error)
	UpdateStoryChapterOrder(ctx context.Context, arg UpdateStoryChapterOrderParams) error
	UpdateStoryStatus(ctx context.Context, arg UpdateStoryStatusParams) (Story, error)
}

var _ Querier = (*Queries)(nil)
