-- name: CreateAsset :one
-- id is generated by the app (so the source_key can embed it before insert).
-- title/original_filename are recorded at session start (SPEC-01 §6); origin is
-- 'upload' for the browser flow, 'import' for the SPEC-02 batch-create.
INSERT INTO assets (id, owner_id, kind, source_key, mime_type, size_bytes, title, original_filename, origin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING *;

-- name: GetAsset :one
SELECT * FROM assets WHERE id = $1;

-- name: GetAssetOwner :one
-- Cheap owner lookup for the RequireOwnerOrPermission extractor (P0.3).
SELECT owner_id FROM assets WHERE id = $1;

-- name: ListAssetsByOwner :many
SELECT * FROM assets
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3;

-- name: ListAssetsByOwnerCursor :many
-- Library keyset page (P0.4). Excludes 'deleting' tombstones. Optional kind and
-- status filters; the status filter is a set so "processing" can also match
-- still-'uploading' sessions (rev 3). Keyset on (created_at, id) DESC, backed by
-- assets_owner_cursor_idx.
SELECT * FROM assets
WHERE owner_id = @owner_id
  AND status <> 'deleting'
  AND (sqlc.narg('kind')::text IS NULL OR kind = sqlc.narg('kind'))
  AND (coalesce(cardinality(@statuses::text[]), 0) = 0 OR status = ANY(@statuses::text[]))
  AND (
        @cursor_created_at::timestamptz IS NULL
        OR created_at < @cursor_created_at::timestamptz
        OR (created_at = @cursor_created_at::timestamptz AND id < @cursor_id::uuid)
      )
ORDER BY created_at DESC, id DESC
LIMIT @lim::int;

-- name: ListAssetsForPurge :many
-- P0.3 janitor: 'deleting' rows past the 15-min grace window (assets_deleting_idx).
SELECT * FROM assets
WHERE status = 'deleting'
  AND updated_at < now() - interval '15 minutes';

-- name: ListAbandonedUploads :many
-- P0.3 janitor: upload sessions the browser never completed (>24h).
SELECT * FROM assets
WHERE status = 'uploading'
  AND updated_at < now() - interval '24 hours';

-- name: MarkAssetProcessing :exec
UPDATE assets
SET status = 'processing',
    updated_at = now()
WHERE id = $1;

-- name: MarkAssetReady :exec
UPDATE assets
SET status = 'ready',
    output_prefix = $2,
    duration_ms = $3,
    width = $4,
    height = $5,
    updated_at = now()
WHERE id = $1;

-- name: MarkAssetImageReady :exec
-- Image ready: sets dimensions but no output_prefix (images have no HLS output).
UPDATE assets
SET status = 'ready',
    width = $2,
    height = $3,
    updated_at = now()
WHERE id = $1;

-- name: MarkAssetFailed :exec
UPDATE assets
SET status = 'failed',
    error_message = $2,
    updated_at = now()
WHERE id = $1;

-- name: SetAssetStatusDeleting :exec
-- P0.3 soft-delete tombstone: excluded from listings until the purge removes it.
UPDATE assets
SET status = 'deleting',
    updated_at = now()
WHERE id = $1;

-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1;
