// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package journalrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// journal module queries (SPEC-05). sqlc input only — regenerate with `make sqlc`;
	// never hand-edit the *.sql.go output. Entries are owner-scoped human-authored
	// rows; the timeline orders and paginates on (occurred_at DESC, id DESC) so a
	// backdated entry sits at its date (P0.2), backed by journal_entries_user_cursor_idx.
	// Create one journal entry. asset_ids is intentionally NOT set — it stays at the
	// table default '{}' until P1.5 attachments land (the service rejects any
	// asset_ids in the request before this query runs). occurred_at is resolved by
	// the service (defaults to now(); backdating/future-dating unlimited).
	CreateEntry(ctx context.Context, arg CreateEntryParams) (JournalEntry, error)
	// Owner-scoped delete. RETURNING id yields no row when the id is missing or owned
	// by another user → the handler answers an idempotent 404; a matched row → 204.
	DeleteEntry(ctx context.Context, arg DeleteEntryParams) (pgtype.UUID, error)
	// Owner-scoped fetch. A row owned by another user (or a missing id) returns no
	// row → the adapter maps pgx.ErrNoRows to ErrEntryNotFound so the handler answers
	// 404 (existence never leaks).
	GetEntry(ctx context.Context, arg GetEntryParams) (JournalEntry, error)
	// Keyset page for the owner, newest first. A NULL @cursor_occurred_at starts at
	// the top; the (occurred_at, id) keyset is backed by journal_entries_user_cursor_idx.
	ListEntriesByUserCursor(ctx context.Context, arg ListEntriesByUserCursorParams) ([]JournalEntry, error)
	// Partial update of any subset of {body_md, mood, occurred_at}. A NULL arg leaves
	// the column unchanged (COALESCE), so nil pointers from the service mean "keep".
	// updated_at always advances; occurred_at is only moved when the caller edits it,
	// so an entry keeps its timeline position unless occurred_at itself changed.
	// Owner-scoped; no matching row → ErrEntryNotFound (404, never leaks existence).
	PatchEntry(ctx context.Context, arg PatchEntryParams) (JournalEntry, error)
}

var _ Querier = (*Queries)(nil)
