// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AccessTokenTokenType.
const (
	AccessTokenTokenTypeBearer AccessTokenTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AccessTokenTokenType enum.
func (e AccessTokenTokenType) Valid() bool {
	switch e {
	case AccessTokenTokenTypeBearer:
		return true
	default:
		return false
	}
}

// Defines values for AssetKind.
const (
	AssetKindAudio AssetKind = "audio"
	AssetKindImage AssetKind = "image"
	AssetKindVideo AssetKind = "video"
)

// Valid indicates whether the value is a known member of the AssetKind enum.
func (e AssetKind) Valid() bool {
	switch e {
	case AssetKindAudio:
		return true
	case AssetKindImage:
		return true
	case AssetKindVideo:
		return true
	default:
		return false
	}
}

// Defines values for AssetStatus.
const (
	AssetStatusFailed     AssetStatus = "failed"
	AssetStatusProcessing AssetStatus = "processing"
	AssetStatusReady      AssetStatus = "ready"
	AssetStatusUploaded   AssetStatus = "uploaded"
)

// Valid indicates whether the value is a known member of the AssetStatus enum.
func (e AssetStatus) Valid() bool {
	switch e {
	case AssetStatusFailed:
		return true
	case AssetStatusProcessing:
		return true
	case AssetStatusReady:
		return true
	case AssetStatusUploaded:
		return true
	default:
		return false
	}
}

// Defines values for AssetUploadSessionUploadMethod.
const (
	PUT AssetUploadSessionUploadMethod = "PUT"
)

// Valid indicates whether the value is a known member of the AssetUploadSessionUploadMethod enum.
func (e AssetUploadSessionUploadMethod) Valid() bool {
	switch e {
	case PUT:
		return true
	default:
		return false
	}
}

// Defines values for ContinuingItemModule.
const (
	Comic ContinuingItemModule = "comic"
	Movie ContinuingItemModule = "movie"
	Music ContinuingItemModule = "music"
	Story ContinuingItemModule = "story"
)

// Valid indicates whether the value is a known member of the ContinuingItemModule enum.
func (e ContinuingItemModule) Valid() bool {
	switch e {
	case Comic:
		return true
	case Movie:
		return true
	case Music:
		return true
	case Story:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusOk       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for LoginResponseTokenType.
const (
	LoginResponseTokenTypeBearer LoginResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the LoginResponseTokenType enum.
func (e LoginResponseTokenType) Valid() bool {
	switch e {
	case LoginResponseTokenTypeBearer:
		return true
	default:
		return false
	}
}

// Defines values for OpsBackupRunStatus.
const (
	OpsBackupRunStatusFailed  OpsBackupRunStatus = "failed"
	OpsBackupRunStatusOk      OpsBackupRunStatus = "ok"
	OpsBackupRunStatusRunning OpsBackupRunStatus = "running"
)

// Valid indicates whether the value is a known member of the OpsBackupRunStatus enum.
func (e OpsBackupRunStatus) Valid() bool {
	switch e {
	case OpsBackupRunStatusFailed:
		return true
	case OpsBackupRunStatusOk:
		return true
	case OpsBackupRunStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for OpsStatusState.
const (
	OpsStatusStateFailed OpsStatusState = "failed"
	OpsStatusStateOk     OpsStatusState = "ok"
	OpsStatusStateStale  OpsStatusState = "stale"
)

// Valid indicates whether the value is a known member of the OpsStatusState enum.
func (e OpsStatusState) Valid() bool {
	switch e {
	case OpsStatusStateFailed:
		return true
	case OpsStatusStateOk:
		return true
	case OpsStatusStateStale:
		return true
	default:
		return false
	}
}

// Defines values for TenantContextKind.
const (
	Household TenantContextKind = "household"
	Org       TenantContextKind = "org"
)

// Valid indicates whether the value is a known member of the TenantContextKind enum.
func (e TenantContextKind) Valid() bool {
	switch e {
	case Household:
		return true
	case Org:
		return true
	default:
		return false
	}
}

// Defines values for ListAssetsParamsKind.
const (
	ListAssetsParamsKindAudio ListAssetsParamsKind = "audio"
	ListAssetsParamsKindImage ListAssetsParamsKind = "image"
	ListAssetsParamsKindVideo ListAssetsParamsKind = "video"
)

// Valid indicates whether the value is a known member of the ListAssetsParamsKind enum.
func (e ListAssetsParamsKind) Valid() bool {
	switch e {
	case ListAssetsParamsKindAudio:
		return true
	case ListAssetsParamsKindImage:
		return true
	case ListAssetsParamsKindVideo:
		return true
	default:
		return false
	}
}

// Defines values for ListAssetsParamsStatus.
const (
	ListAssetsParamsStatusFailed     ListAssetsParamsStatus = "failed"
	ListAssetsParamsStatusProcessing ListAssetsParamsStatus = "processing"
	ListAssetsParamsStatusReady      ListAssetsParamsStatus = "ready"
)

// Valid indicates whether the value is a known member of the ListAssetsParamsStatus enum.
func (e ListAssetsParamsStatus) Valid() bool {
	switch e {
	case ListAssetsParamsStatusFailed:
		return true
	case ListAssetsParamsStatusProcessing:
		return true
	case ListAssetsParamsStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for CompleteAssetUpload202JSONResponseBodyStatus.
const (
	CompleteAssetUpload202JSONResponseBodyStatusProcessing CompleteAssetUpload202JSONResponseBodyStatus = "processing"
)

// Valid indicates whether the value is a known member of the CompleteAssetUpload202JSONResponseBodyStatus enum.
func (e CompleteAssetUpload202JSONResponseBodyStatus) Valid() bool {
	switch e {
	case CompleteAssetUpload202JSONResponseBodyStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for GetAssetVariantParamsVariant.
const (
	Medium GetAssetVariantParamsVariant = "medium"
	Poster GetAssetVariantParamsVariant = "poster"
	Thumb  GetAssetVariantParamsVariant = "thumb"
)

// Valid indicates whether the value is a known member of the GetAssetVariantParamsVariant enum.
func (e GetAssetVariantParamsVariant) Valid() bool {
	switch e {
	case Medium:
		return true
	case Poster:
		return true
	case Thumb:
		return true
	default:
		return false
	}
}

// Defines values for ForgotPassword202JSONResponseBodyStatus.
const (
	Accepted ForgotPassword202JSONResponseBodyStatus = "accepted"
)

// Valid indicates whether the value is a known member of the ForgotPassword202JSONResponseBodyStatus enum.
func (e ForgotPassword202JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	default:
		return false
	}
}

// Defines values for Register201JSONResponseBodyStatus.
const (
	Registered Register201JSONResponseBodyStatus = "registered"
)

// Valid indicates whether the value is a known member of the Register201JSONResponseBodyStatus enum.
func (e Register201JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Registered:
		return true
	default:
		return false
	}
}

// Defines values for ResetPassword200JSONResponseBodyStatus.
const (
	PasswordUpdated ResetPassword200JSONResponseBodyStatus = "password_updated"
)

// Valid indicates whether the value is a known member of the ResetPassword200JSONResponseBodyStatus enum.
func (e ResetPassword200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case PasswordUpdated:
		return true
	default:
		return false
	}
}

// Defines values for ListNotificationsParamsStatus.
const (
	All    ListNotificationsParamsStatus = "all"
	Unread ListNotificationsParamsStatus = "unread"
)

// Valid indicates whether the value is a known member of the ListNotificationsParamsStatus enum.
func (e ListNotificationsParamsStatus) Valid() bool {
	switch e {
	case All:
		return true
	case Unread:
		return true
	default:
		return false
	}
}

// AccessToken defines model for AccessToken.
type AccessToken struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn seconds until expiry
	ExpiresIn int                  `json:"expires_in"`
	TokenType AccessTokenTokenType `json:"token_type"`
}

// AccessTokenTokenType defines model for AccessToken.TokenType.
type AccessTokenTokenType string

// Asset defines model for Asset.
type Asset struct {
	CreatedAt  time.Time `json:"createdAt"`
	DurationMs *int      `json:"durationMs,omitempty"`

	// Error Failure reason; present when `status` is `failed`.
	Error  *string `json:"error,omitempty"`
	Height *int    `json:"height,omitempty"`

	// HlsUrl Master playlist URL; present once `status` is `ready`.
	HlsUrl    *string            `json:"hlsUrl,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Kind      AssetKind          `json:"kind"`
	MimeType  string             `json:"mimeType"`
	SizeBytes int64              `json:"sizeBytes"`
	Status    AssetStatus        `json:"status"`
	Width     *int               `json:"width,omitempty"`
}

// AssetKind defines model for AssetKind.
type AssetKind string

// AssetStatus defines model for AssetStatus.
type AssetStatus string

// AssetUploadSession defines model for AssetUploadSession.
type AssetUploadSession struct {
	Asset Asset `json:"asset"`

	// Upload Presigned request the client performs to store the original.
	Upload struct {
		Headers *map[string]string             `json:"headers,omitempty"`
		Method  AssetUploadSessionUploadMethod `json:"method"`
		Url     string                         `json:"url"`
	} `json:"upload"`
}

// AssetUploadSessionUploadMethod defines model for AssetUploadSession.Upload.Method.
type AssetUploadSessionUploadMethod string

// ContinuingItem One "continue watching / reading / listening" entry for the cross-domain
// `/continue` rail [D-20]. Aggregated from each vertical's progress table.
type ContinuingItem struct {
	Id     openapi_types.UUID   `json:"id"`
	Module ContinuingItemModule `json:"module"`

	// Progress Fractional completion 0..1.
	Progress     float32   `json:"progress"`
	ResourceUrl  *string   `json:"resourceUrl,omitempty"`
	ThumbnailUrl *string   `json:"thumbnailUrl,omitempty"`
	Title        string    `json:"title"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// ContinuingItemModule defines model for ContinuingItem.Module.
type ContinuingItemModule string

// CreateAssetRequest defines model for CreateAssetRequest.
type CreateAssetRequest struct {
	ContentType *string `json:"contentType,omitempty"`
	Filename    string  `json:"filename"`
	SizeBytes   int64   `json:"sizeBytes"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	AvatarUrl   *string             `json:"avatarUrl,omitempty"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`

	// Roles Role codes (e.g. ["user","creator"]). Frontend uses these to render UI affordances; the server is the authority on perm checks.
	Roles []string `json:"roles"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ForgotPasswordRequest defines model for ForgotPasswordRequest.
type ForgotPasswordRequest struct {
	Email openapi_types.Email `json:"email"`
}

// Health defines model for Health.
type Health struct {
	Cache  *bool        `json:"cache,omitempty"`
	Db     *bool        `json:"db,omitempty"`
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// JournalEntry defines model for JournalEntry.
type JournalEntry struct {
	AssetIds   []openapi_types.UUID `json:"asset_ids"`
	BodyMd     string               `json:"body_md"`
	CreatedAt  time.Time            `json:"created_at"`
	Id         openapi_types.UUID   `json:"id"`
	Mood       *string              `json:"mood,omitempty"`
	OccurredAt time.Time            `json:"occurred_at"`
	UpdatedAt  time.Time            `json:"updated_at"`
}

// JournalEntryWrite Create requires body_md; PATCH accepts any subset of the fields. `asset_ids`
// is rejected with 422 `journal/invalid-asset` until photo attachments (P1.5).
type JournalEntryWrite struct {
	BodyMd *string `json:"body_md,omitempty"`
	Mood   *string `json:"mood,omitempty"`

	// OccurredAt Optional; defaults to now. Backdating and future-dating are allowed.
	OccurredAt *time.Time `json:"occurred_at,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`

	// Remember Persist the session (durable refresh cookie) vs a session cookie.
	Remember *bool `json:"remember,omitempty"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn seconds until expiry
	ExpiresIn int                    `json:"expires_in"`
	TokenType LoginResponseTokenType `json:"token_type"`
	User      struct {
		DisplayName string              `json:"display_name"`
		Email       openapi_types.Email `json:"email"`
		Id          openapi_types.UUID  `json:"id"`
		Roles       []string            `json:"roles"`
	} `json:"user"`
}

// LoginResponseTokenType defines model for LoginResponse.TokenType.
type LoginResponseTokenType string

// Money Exact monetary amount [D-14/D-15]. `amount` is a decimal string to avoid float error.
type Money struct {
	// Amount Decimal string, e.g. "1234.56" (numeric(20,8) at rest).
	Amount string `json:"amount"`

	// Currency ISO 4217 code, e.g. "USD".
	Currency string `json:"currency"`
}

// Notification defines model for Notification.
type Notification struct {
	Body      *string   `json:"body,omitempty"`
	CreatedAt time.Time `json:"created_at"`

	// Data Target ids / links — e.g. `href` for the bell's click-through.
	Data map[string]interface{} `json:"data"`
	Id   openapi_types.UUID     `json:"id"`

	// ReadAt When the notification was marked read; null while unread.
	ReadAt *time.Time `json:"read_at"`
	Title  string     `json:"title"`

	// Type Open type registry (e.g. `media.asset_ready`). See notify/README.md.
	Type string `json:"type"`
}

// NotificationList defines model for NotificationList.
type NotificationList struct {
	Items []Notification `json:"items"`

	// NextCursor Keyset cursor for the next page; absent/null on the last page.
	NextCursor *string `json:"next_cursor,omitempty"`

	// UnreadCount Unread badge count for the bell.
	UnreadCount int `json:"unread_count"`
}

// OpsBackupRun One row of the backup-run ledger (`ops_backup_runs`).
type OpsBackupRun struct {
	Error      *string            `json:"error,omitempty"`
	FinishedAt *time.Time         `json:"finished_at,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	SizeBytes  *int64             `json:"size_bytes,omitempty"`
	StartedAt  time.Time          `json:"started_at"`
	Status     OpsBackupRunStatus `json:"status"`
	StorageKey *string            `json:"storage_key,omitempty"`
}

// OpsBackupRunStatus defines model for OpsBackupRun.Status.
type OpsBackupRunStatus string

// OpsStatus Freshness sentinel for the nightly Postgres backup (P0.5). `last_success_at`
// and `hours_since_success` are both null when a backup has never succeeded.
type OpsStatus struct {
	// HoursSinceSuccess Hours since the last success; null if none.
	HoursSinceSuccess *float32 `json:"hours_since_success,omitempty"`

	// LastRun The most recently started run of any status; null if none.
	LastRun *OpsBackupRun `json:"last_run,omitempty"`

	// LastSuccessAt Completion time of the most recent successful run; null if none.
	LastSuccessAt *time.Time `json:"last_success_at,omitempty"`

	// State `failed` (most recent completed run failed) → `stale` (no success within
	// 26 h, incl. never-ran) → `ok`. A running run never changes state.
	State OpsStatusState `json:"state"`
}

// OpsStatusState `failed` (most recent completed run failed) → `stale` (no success within
// 26 h, incl. never-ran) → `ok`. A running run never changes state.
type OpsStatusState string

// PaginatedResult Cursor-paginated envelope. Concrete endpoints override `items` with their
// element type (OpenAPI has no generics — compose with `allOf` + an `items`
// override, or document the element type in the operation).
type PaginatedResult struct {
	Items []interface{} `json:"items"`

	// NextCursor Opaque cursor for the next page; null on the last page.
	NextCursor *string `json:"nextCursor,omitempty"`

	// Total Total count when cheap to compute; otherwise omitted.
	Total *int `json:"total,omitempty"`
}

// Problem RFC 7807 problem detail, served as `application/problem+json`. `type` is a
// stable URI (also the i18n key); Portal adds the extensions below.
type Problem struct {
	// Code Portal-stable machine slug (e.g. `invalid_credentials`).
	Code *string `json:"code,omitempty"`

	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// EnrollmentUrl For MFA-enrollment (403) — where to enroll a second factor [D-28].
	EnrollmentUrl *string `json:"enrollment_url,omitempty"`

	// Instance URI reference identifying the specific occurrence.
	Instance *string `json:"instance,omitempty"`

	// RequiredAcr For step-up (403) — the ACR the caller must satisfy [D-27].
	RequiredAcr *string `json:"required_acr,omitempty"`

	// Status HTTP status code, repeated for convenience.
	Status int `json:"status"`

	// Title Short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type Stable problem-type URI (i18n key).
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// DisplayName Optional; defaults to the email local-part.
	DisplayName *string             `json:"display_name,omitempty"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	NewPassword string `json:"new_password"`

	// Token The one-time reset token from the email link.
	Token string `json:"token"`
}

// TenantContext Resolved tenant scope for the `/t/{tenant}/…` prefix [D-23]. Multi-tenancy
// is deferred to Phase 1; v1 runs single-tenant (`me`).
type TenantContext struct {
	Kind     *TenantContextKind `json:"kind,omitempty"`
	Slug     string             `json:"slug"`
	TenantId openapi_types.UUID `json:"tenantId"`
}

// TenantContextKind defines model for TenantContext.Kind.
type TenantContextKind string

// UnreadCount defines model for UnreadCount.
type UnreadCount struct {
	UnreadCount int `json:"unread_count"`
}

// User defines model for User.
type User struct {
	AvatarUrl   *string             `json:"avatarUrl,omitempty"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
}

// AssetID defines model for AssetID.
type AssetID = openapi_types.UUID

// TenantSlug defines model for TenantSlug.
type TenantSlug = string

// BadRequest RFC 7807 problem detail, served as `application/problem+json`. `type` is a
// stable URI (also the i18n key); Portal adds the extensions below.
type BadRequest = Problem

// Forbidden RFC 7807 problem detail, served as `application/problem+json`. `type` is a
// stable URI (also the i18n key); Portal adds the extensions below.
type Forbidden = Problem

// NotFound RFC 7807 problem detail, served as `application/problem+json`. `type` is a
// stable URI (also the i18n key); Portal adds the extensions below.
type NotFound = Problem

// TooManyRequests RFC 7807 problem detail, served as `application/problem+json`. `type` is a
// stable URI (also the i18n key); Portal adds the extensions below.
type TooManyRequests = Problem

// Unauthorized RFC 7807 problem detail, served as `application/problem+json`. `type` is a
// stable URI (also the i18n key); Portal adds the extensions below.
type Unauthorized = Problem

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListAssetsParams defines parameters for ListAssets.
type ListAssetsParams struct {
	// Kind Filter by asset kind.
	Kind *ListAssetsParamsKind `form:"kind,omitempty" json:"kind,omitempty"`

	// Status Filter by status; `processing` includes still-`uploading` sessions.
	Status *ListAssetsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Cursor Opaque keyset cursor from a prior page's `next_cursor`.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAssetsParamsKind defines parameters for ListAssets.
type ListAssetsParamsKind string

// ListAssetsParamsStatus defines parameters for ListAssets.
type ListAssetsParamsStatus string

// CompleteAssetUpload202JSONResponseBodyStatus defines parameters for CompleteAssetUpload.
type CompleteAssetUpload202JSONResponseBodyStatus string

// GetAssetVariantParamsVariant defines parameters for GetAssetVariant.
type GetAssetVariantParamsVariant string

// ForgotPassword202JSONResponseBodyStatus defines parameters for ForgotPassword.
type ForgotPassword202JSONResponseBodyStatus string

// RefreshTokenJSONBody defines parameters for RefreshToken.
type RefreshTokenJSONBody struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// Register201JSONResponseBodyStatus defines parameters for Register.
type Register201JSONResponseBodyStatus string

// ResetPassword200JSONResponseBodyStatus defines parameters for ResetPassword.
type ResetPassword200JSONResponseBodyStatus string

// ListJournalEntriesParams defines parameters for ListJournalEntries.
type ListJournalEntriesParams struct {
	// Cursor Opaque keyset cursor from a prior page's next_cursor.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListNotificationsParams defines parameters for ListNotifications.
type ListNotificationsParams struct {
	Status *ListNotificationsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Cursor Opaque keyset cursor from a prior page's `next_cursor`.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListNotificationsParamsStatus defines parameters for ListNotifications.
type ListNotificationsParamsStatus string

// MarkAllNotificationsReadParams defines parameters for MarkAllNotificationsRead.
type MarkAllNotificationsReadParams struct {
	// Before Keyset watermark cursor; absent marks all unread read.
	Before *string `form:"before,omitempty" json:"before,omitempty"`
}

// CreateAssetUploadJSONRequestBody defines body for CreateAssetUpload for application/json ContentType.
type CreateAssetUploadJSONRequestBody = CreateAssetRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = ForgotPasswordRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody RefreshTokenJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// CreateJournalEntryJSONRequestBody defines body for CreateJournalEntry for application/json ContentType.
type CreateJournalEntryJSONRequestBody = JournalEntryWrite

// PatchJournalEntryJSONRequestBody defines body for PatchJournalEntry for application/json ContentType.
type PatchJournalEntryJSONRequestBody = JournalEntryWrite

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["enrollment_url"]; found {
		err = json.Unmarshal(raw, &a.EnrollmentUrl)
		if err != nil {
			return fmt.Errorf("error reading 'enrollment_url': %w", err)
		}
		delete(object, "enrollment_url")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["required_acr"]; found {
		err = json.Unmarshal(raw, &a.RequiredAcr)
		if err != nil {
			return fmt.Errorf("error reading 'required_acr': %w", err)
		}
		delete(object, "required_acr")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.EnrollmentUrl != nil {
		object["enrollment_url"], err = json.Marshal(a.EnrollmentUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'enrollment_url': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.RequiredAcr != nil {
		object["required_acr"], err = json.Marshal(a.RequiredAcr)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'required_acr': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List the caller's assets
	// (GET /assets)
	ListAssets(w http.ResponseWriter, r *http.Request, params ListAssetsParams)
	// Begin a media upload
	// (POST /assets)
	CreateAssetUpload(w http.ResponseWriter, r *http.Request)
	// Delete an asset (owner, or `assets:delete:any`)
	// (DELETE /assets/{id})
	DeleteAsset(w http.ResponseWriter, r *http.Request, id AssetID)
	// Get asset metadata
	// (GET /assets/{id})
	GetAsset(w http.ResponseWriter, r *http.Request, id AssetID)
	// Confirm the upload and enqueue processing
	// (POST /assets/{id}/complete)
	CompleteAssetUpload(w http.ResponseWriter, r *http.Request, id AssetID)
	// Public HLS proxy (manifest + segments)
	// (GET /assets/{id}/hls/{path})
	GetAssetHLS(w http.ResponseWriter, r *http.Request, id AssetID, path string)
	// Download the original file (owner-only)
	// (GET /assets/{id}/original)
	DownloadAssetOriginal(w http.ResponseWriter, r *http.Request, id AssetID)
	// API-proxied upload of the original bytes (dev path)
	// (PUT /assets/{id}/source)
	UploadAssetSource(w http.ResponseWriter, r *http.Request, id AssetID)
	// Stream a derived variant (public-ish)
	// (GET /assets/{id}/variants/{variant})
	GetAssetVariant(w http.ResponseWriter, r *http.Request, id AssetID, variant GetAssetVariantParamsVariant)
	// Request a password-reset email (SPEC-04 P0.3)
	// (POST /auth/forgot-password)
	ForgotPassword(w http.ResponseWriter, r *http.Request)
	// Local password login
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Revoke current session and bump token_version
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Revoke every session for the current user
	// (POST /auth/logout-all)
	LogoutAll(w http.ResponseWriter, r *http.Request)
	// Get the currently authenticated user
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Rotate refresh token, mint new access token
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Create a local account
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// Consume a reset token and set a new password (SPEC-04 P0.3)
	// (POST /auth/reset-password)
	ResetPassword(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List the caller's journal entries (newest occurred_at first)
	// (GET /journal/entries)
	ListJournalEntries(w http.ResponseWriter, r *http.Request, params ListJournalEntriesParams)
	// Create a journal entry
	// (POST /journal/entries)
	CreateJournalEntry(w http.ResponseWriter, r *http.Request)
	// Delete a journal entry (idempotent)
	// (DELETE /journal/entries/{id})
	DeleteJournalEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Fetch one journal entry
	// (GET /journal/entries/{id})
	GetJournalEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Partially update a journal entry
	// (PATCH /journal/entries/{id})
	PatchJournalEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List the caller's notifications (SPEC-04 P0.1)
	// (GET /me/notifications)
	ListNotifications(w http.ResponseWriter, r *http.Request, params ListNotificationsParams)
	// Mark all notifications read, optionally up to a watermark
	// (POST /me/notifications/read-all)
	MarkAllNotificationsRead(w http.ResponseWriter, r *http.Request, params MarkAllNotificationsReadParams)
	// Mark one notification read (idempotent)
	// (POST /me/notifications/{id}/read)
	MarkNotificationRead(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Backup freshness sentinel (admin)
	// (GET /ops/status)
	GetOpsStatus(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List the caller's assets
// (GET /assets)
func (_ Unimplemented) ListAssets(w http.ResponseWriter, r *http.Request, params ListAssetsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Begin a media upload
// (POST /assets)
func (_ Unimplemented) CreateAssetUpload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an asset (owner, or `assets:delete:any`)
// (DELETE /assets/{id})
func (_ Unimplemented) DeleteAsset(w http.ResponseWriter, r *http.Request, id AssetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get asset metadata
// (GET /assets/{id})
func (_ Unimplemented) GetAsset(w http.ResponseWriter, r *http.Request, id AssetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Confirm the upload and enqueue processing
// (POST /assets/{id}/complete)
func (_ Unimplemented) CompleteAssetUpload(w http.ResponseWriter, r *http.Request, id AssetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Public HLS proxy (manifest + segments)
// (GET /assets/{id}/hls/{path})
func (_ Unimplemented) GetAssetHLS(w http.ResponseWriter, r *http.Request, id AssetID, path string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download the original file (owner-only)
// (GET /assets/{id}/original)
func (_ Unimplemented) DownloadAssetOriginal(w http.ResponseWriter, r *http.Request, id AssetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// API-proxied upload of the original bytes (dev path)
// (PUT /assets/{id}/source)
func (_ Unimplemented) UploadAssetSource(w http.ResponseWriter, r *http.Request, id AssetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream a derived variant (public-ish)
// (GET /assets/{id}/variants/{variant})
func (_ Unimplemented) GetAssetVariant(w http.ResponseWriter, r *http.Request, id AssetID, variant GetAssetVariantParamsVariant) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a password-reset email (SPEC-04 P0.3)
// (POST /auth/forgot-password)
func (_ Unimplemented) ForgotPassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Local password login
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke current session and bump token_version
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke every session for the current user
// (POST /auth/logout-all)
func (_ Unimplemented) LogoutAll(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the currently authenticated user
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rotate refresh token, mint new access token
// (POST /auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a local account
// (POST /auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Consume a reset token and set a new password (SPEC-04 P0.3)
// (POST /auth/reset-password)
func (_ Unimplemented) ResetPassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List the caller's journal entries (newest occurred_at first)
// (GET /journal/entries)
func (_ Unimplemented) ListJournalEntries(w http.ResponseWriter, r *http.Request, params ListJournalEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a journal entry
// (POST /journal/entries)
func (_ Unimplemented) CreateJournalEntry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a journal entry (idempotent)
// (DELETE /journal/entries/{id})
func (_ Unimplemented) DeleteJournalEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch one journal entry
// (GET /journal/entries/{id})
func (_ Unimplemented) GetJournalEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Partially update a journal entry
// (PATCH /journal/entries/{id})
func (_ Unimplemented) PatchJournalEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List the caller's notifications (SPEC-04 P0.1)
// (GET /me/notifications)
func (_ Unimplemented) ListNotifications(w http.ResponseWriter, r *http.Request, params ListNotificationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Mark all notifications read, optionally up to a watermark
// (POST /me/notifications/read-all)
func (_ Unimplemented) MarkAllNotificationsRead(w http.ResponseWriter, r *http.Request, params MarkAllNotificationsReadParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Mark one notification read (idempotent)
// (POST /me/notifications/{id}/read)
func (_ Unimplemented) MarkNotificationRead(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Backup freshness sentinel (admin)
// (GET /ops/status)
func (_ Unimplemented) GetOpsStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAssets operation middleware
func (siw *ServerInterfaceWrapper) ListAssets(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAssetsParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAssets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAssetUpload operation middleware
func (siw *ServerInterfaceWrapper) CreateAssetUpload(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAssetUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAsset operation middleware
func (siw *ServerInterfaceWrapper) DeleteAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAsset(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsset(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteAssetUpload operation middleware
func (siw *ServerInterfaceWrapper) CompleteAssetUpload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteAssetUpload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAssetHLS operation middleware
func (siw *ServerInterfaceWrapper) GetAssetHLS(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "path" -------------
	var path string

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetHLS(w, r, id, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadAssetOriginal operation middleware
func (siw *ServerInterfaceWrapper) DownloadAssetOriginal(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadAssetOriginal(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadAssetSource operation middleware
func (siw *ServerInterfaceWrapper) UploadAssetSource(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadAssetSource(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAssetVariant operation middleware
func (siw *ServerInterfaceWrapper) GetAssetVariant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "variant" -------------
	var variant GetAssetVariantParamsVariant

	err = runtime.BindStyledParameterWithOptions("simple", "variant", chi.URLParam(r, "variant"), &variant, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "variant", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetVariant(w, r, id, variant)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ForgotPassword operation middleware
func (siw *ServerInterfaceWrapper) ForgotPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ForgotPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutAll operation middleware
func (siw *ServerInterfaceWrapper) LogoutAll(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutAll(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListJournalEntries operation middleware
func (siw *ServerInterfaceWrapper) ListJournalEntries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListJournalEntriesParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListJournalEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) CreateJournalEntry(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJournalEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) DeleteJournalEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteJournalEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) GetJournalEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJournalEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) PatchJournalEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchJournalEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNotifications operation middleware
func (siw *ServerInterfaceWrapper) ListNotifications(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNotificationsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNotifications(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkAllNotificationsRead operation middleware
func (siw *ServerInterfaceWrapper) MarkAllNotificationsRead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params MarkAllNotificationsReadParams

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkAllNotificationsRead(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkNotificationRead operation middleware
func (siw *ServerInterfaceWrapper) MarkNotificationRead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkNotificationRead(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpsStatus operation middleware
func (siw *ServerInterfaceWrapper) GetOpsStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpsStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets", wrapper.ListAssets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/assets", wrapper.CreateAssetUpload)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/assets/{id}", wrapper.DeleteAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}", wrapper.GetAsset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/assets/{id}/complete", wrapper.CompleteAssetUpload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}/hls/{path}", wrapper.GetAssetHLS)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}/original", wrapper.DownloadAssetOriginal)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/assets/{id}/source", wrapper.UploadAssetSource)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}/variants/{variant}", wrapper.GetAssetVariant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/forgot-password", wrapper.ForgotPassword)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout-all", wrapper.LogoutAll)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/reset-password", wrapper.ResetPassword)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/journal/entries", wrapper.ListJournalEntries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/journal/entries", wrapper.CreateJournalEntry)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/journal/entries/{id}", wrapper.DeleteJournalEntry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/journal/entries/{id}", wrapper.GetJournalEntry)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/journal/entries/{id}", wrapper.PatchJournalEntry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/notifications", wrapper.ListNotifications)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/me/notifications/read-all", wrapper.MarkAllNotificationsRead)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/me/notifications/{id}/read", wrapper.MarkNotificationRead)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ops/status", wrapper.GetOpsStatus)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3ZbuPIluCvHOg2UJJLi+3M2pxoNJxble/NrDTs9K0BSh4zRB6JcU1GsCKCUuomEuinAfp1MJ8wM78w",
	"7/Mp9SWDOBFBkRJlybn41nT3ky0usZw4+8b3nVjmhRQojO6cvO8UTLEcDSr6dao1mrPn9l8uOiedgpm0",
	"0+8IlmPnpMOTTr+j8LeSK0w6J0aV2O/oOMWc2TemUuXMdE46ZUlPmmVh39JGcTHrfPjQ77xFwYS5zMqZ",
	"fT5BHSteGC7tVO4e6KycwVQqMClCNDKj94ZufBj9/q//O4JC4ZS/G0KUYwQaM4yNpkdjlmWovtJjUaDS",
	"UrAMdCwLHMLrMjN84EYBJUvDxQy4hgSnqBQmYCScp0wjHEFXI45F9KfRCkgjt0E9cgt8JoXBdybqPYH5",
	"EahSaNBczDL0MwzHotNvA567fScA1wH2wT6sCyk00uk8ZckF/laiNvZXbFci6F9WFBmPmYXkqFBykmH+",
	"9d+0Bev72vD/pHDaOem0bu7cveUmbR7Ma5bZk8UElJ/8Q7/zUqoJTxIUD7mS09KkKIwdH5M+TEoDGYtv",
	"NRSocq41lwK6UoE2WAzKAgKke3bFP0vzUpYiecgFX6CWpYoRhDQwpdktFUj5momlP0r9oAtiBiHjOTcw",
	"gkzGt7I0YBQvCqSlXQlWmlQq/nd8UEC9tqcnZiAVcDFnGU8gVpjYw2aZJt7hRyEuFceo9Vt569CvULJA",
	"ZbgjEkY3b0y4u0ZU/Q6+K7hCfcPFJhPSGEuRaCiF4RnQk8sVJ+PC4AyVHYSGv3HX33dQlHnn5NfOU2QK",
	"Vee6jfetyP7X5hobK2qMvBpHTv6GMREecejNXccKLVGcmgYjTpjBgeE5bnLjficpFZ3maxpAlFnGJhkG",
	"rrS5ZVRKqk2QvWQ8KxWCQqaleGI5tEZhYJGigEgbZkodWX4bTRnPMImGlie2z7ZaXIp8lpr9FpZm+kpl",
	"myt7zbRBBUXGlhnXBq4uXq2WJ0WMzeUpZMmSVrcSZIrvs1ie7CH++p1b7rjPXTRCx/sX7hhFznN861Fs",
	"YzTN/45Pl8YdfzU3F+bbx60Y67a61/yX7tEP/c6CJybd5xTWEJwA4Gf0G69tp774fg11t+L7XzzkAp3N",
	"eYKy0++wMuH2L8/ZDFvIzr9+WW09DFAWmWQJ2lUVSlpitM/bPbDEErxD1e0jXtH7l0gyp4UHBSLdCWo7",
	"olvMJv6eK9R8JlaC1yk6Gbf4W6Cyh66t9qKNVEg3peIzLlg2dBurLSlFlngljyUJt1Ow7LzxyMZWNw4j",
	"R5PKxkmcX71thVLpCHKNku7mivadao5NXFjnoQS+CnptuGN1NS5KLmZnBvNNAL8RCGOScVyUCAtm4tRK",
	"oZFlZon7z3IOFFzMxh1AYdSyUk5jJbUeJDJnXIxFNArjRKAYz+DX54Pjw+shnM5mCmcWw2GqZA7I4hTm",
	"Fuoxy77SUCg5U6g1GEtfTn1sHt2e7CWXSZk1xFEu59xSW15qHhNBShJnscx53HpsYTEtbF6x2CENWFzO",
	"0P6Aw+HwqMExp5lk9lRy9o7ndhVHlu6F+/+wmlGU+cSxJeVVpKt9EKbfMWmZTwTjWfvzO1m14SZr56dl",
	"kdxPgq7howd/3/E+N08NoPUJWnGVuCDxhJqOvybknTYWREKCU1ZmdpV13UzGBs1AG4Usb4PglGfoTJJP",
	"FiprEKhGro/TutdSKRTmSiPpEyzL3kw7J7/ezS7p6Q/9dZgomWELul7IDCGWCWro4nA2hF/HnVKjGnf6",
	"YydxpBp3rntDeKkIqgmUGsmU1Gh5qkKRoIKrM2DTqVQJEzHqJ0T4GtUcldUZ7C+vMJslSEGGCMQpxrfa",
	"kgU3mN/JWplSbLkBSLenTchdf+h3Xqy0sEIhWUIB2deRJWk/4xy1tuKyxeBsLoNGWD3fdpIvpZpJc860",
	"XkiVbEVczBlvkqu7soum3FNtE/+ELHOaydquWZzWtzaRMkMmSN+dtF/XG9qBvO1YA2WmSEXYqc37AdqW",
	"+WdZKsGyF1ZwbFETbnjiuHzAlZ2Mvok7/c5EJsubPGk9bK9c3bB7GAZ7yxunCuzkuTKOLcHfbxGeW97j",
	"nTYVNICmX4N1c0ENEDWm3XWevyhucJPzOEYefA8a/BKewPnp22c/gTX9CqOBiSXocqLRgJwSI5lyzBI9",
	"hKhaajQWXINCOzsmsOAmhcfHxxD9zS1j5G3lAb0Reau1SKWRwIxhcZpbFgrd86PhN7021aKGOjl79wrF",
	"zBLV8eHh4SHJ7XDl6I7zr734/cZb90WONQWtcCrHE/CyjtRdIRdDeMri24SRL4+JBKalKRUOwhWFwLJM",
	"LjBpaCd3Y8/Gab+SMy4+nan1O4VnkI2nq4stLyjMkTSkupifskzjuufkHJXm3jTQ6H1g1rSfZBYJpwp1",
	"CrGUtxx7MNfAqqfcxeFq+oontnLh2i6ut8PKeSv3l+p1V86mcC+9htC8mnBtbfqbrVrMPU5mT15XaRkf",
	"KdFp1LCIxvr7W6X9unWkG56luk7wWgpcblLPi3csNpBLgYapJbBclsJYu+To8ej54Oiba8tr6CI5QBgk",
	"GPOcZeA2ZUmNzSVPgJR6IP/PpmHpRtic/XljsD6QFjbuHB0/ejz85ttxB7qizFHxuHt82P++B8yAQm16",
	"NAMzBpUd5b8O/uXXw8EP1193x+Oh+6/3L//UdkTERkTcAoezyzfw+PjoO9IHq4VcXT4fd4bOVAkM61GD",
	"fT3a6cZzW6/N3UYZP0vDp14730Rmy4E/m+ROmGHbLXzHgdeiLkzN0ABPNNm64lbD7//6PxyMolThNKrs",
	"3Qlm1l6NMx7fDkyqZDlLa9xjteF9aQpZO9f/JUVBM4oa5GDBNORM3ZI7hCVPwIoWWKQ8QyiFvbSV1X+C",
	"VWgqW6spl+wKl4XlsDOujVp6KyPKMeFs6CS4cyj2hnCJfi/L0cWL0+evXwzzZLifAmOcvyyYk3TAK9A1",
	"sGQX7r3ibVKsYmjVP3ex6wYut6iiAt+Zm7hUus1T/BdcWnXH3a7Qyr4CBZvhE2ATjcKM6GClQ4GMaXd3",
	"L6+xw4ObuJ0jXdFdmLBkZm1DywzruD3cbeE6GK3N0wb3N4W2CkpZXJSi3e+k5CIofhN6cqBKARkmM1TQ",
	"jWShb9z1G1UKHfU2GW/lj98JlikXXKd385LP5eS2lv/NZKsLYbc3Xxum7sv3Nk04VQrhXLpkzN3hz9VG",
	"KjbDm1snQnfA4U4/d23pW5Bi5Yle966hTgVqDZYCuMBsRR98lppsCedSmxkZFIQW0D0/tEo9RJZEbnTp",
	"QkrMRGNhFeIolaXSN5qLGMPdiBTjiTRpYJ4ogIUBU6ZB4BwV0OOYYNJmMrSMu7mfn+xDQA+tyNg/7Tk3",
	"n4KQ4i66XjkJaYvKkdJ+emWDAD9cb4i9FCGX2qocMQoLXn92YKlQTp15Roe1a7lheasTaLEJVx5Ti8KB",
	"8GsrCMCZlpldwuakH0e0dgst8iuE4qBbX4L363oguEd68Pt/++8UJ8swgq6QYaFkjXIxFsffQtoHLuJs",
	"6NBnoJjwr8nbaAin4ImRhnUYFqdMzFATiL3Pu+F8ofnuotsWF0y7h+qczbiwIvICNVlRG2dD4mhQhOcA",
	"xRwzyhx5JkWs0CCgSArJrSkt56gUTxAikgWRM8pNilyNBWZoDW6nGXStknB6fuboSsIMhdV2nX5FGKvR",
	"vR0RSkfwNTARxh2LMFMfpIJExqUbOkVoTMOdnLQUSlK51czfEPJbRPezLZL7TcF+K/EOyf3xIttIw1pi",
	"t2/tZS+kiU3FKbLCmiQWdKXBJyBNimrBNYLMuTHO1L9vnJLg0Yo3PlnhXtr0xctn8N33h9+BT5CABA3j",
	"Wd+5jBNgGqJteRTRECK7CmeLjYWmeBBcXZxBl2VaEmz50fcCbnHZewLnUlkQsSRxfmh8Z1BYw15bbUYu",
	"2vAg+ITXXAg00sBPmLM45QJdIpbXar2f6aaWk+E0kk0LhDbcIhDKnImB1ZpoEnxXZEw4xV4XGFul0h6u",
	"SbkG7xISMbZOgULJLLMUcFO2hf1fSgWvX54OVs9B9/Hhox4R3iJFRf59d5fcIbEUCUxZbKSiqN331y1J",
	"AJv6kD0hEbfA0x6ZwinSFoATxKZLsqhTXG23uc1d0wWsvWGxat9zyHpabdZOd/rsopYfB3lpBTEzXE+X",
	"tNnvrod3a1Rr5/j27bkXjN6cVligi25KBbEUcxR87ezqeTPB0moOe5lKZfqQNrFEl3nO1DKIy0BUdtTh",
	"dsd4IzA2kaU5mWRMOJd+Y06H737UAXFToraKyHafyxo7WbPW7ggMXJDdiGqrd3HdybWPY5TYQM54BpmM",
	"WTYomDLtJPT5XJc1f8n3+4VzdjgSL1Dj7oiSwMXNJy3NJ1q1SB4rTYVTsUDZxQA96aL3NRBzcbvbiA8p",
	"Xo31tm27kV3aEs9ELTMrQnweK+W27syTJQp/dN3IgY2XFFVoyX7dktEK3SjHqFWvuF3Ly5HKWlypLDWm",
	"Mttib/ns383zoNnOkv1SiRtADm/60dvg64z/Z8EzsOZnXvMb7NAadpr/V61+azZnhqmPTFzw/ODnh/J5",
	"7+HAprW0+q01xqXiZnlprTHv56TUyNPSBW3dr5dhCX/+5W3HZ3hSIMKlUVYjp8YULmuUi6ncpsCQyNOY",
	"TQep1FYgkS8OiowZu1c4PT8bjsVYvLU6RqVQ+yj+wYHP1LWyRpUmPTioqItkXiyFUSw2w7G4dPF/bcqJ",
	"hu6PskcRKPvk22WBl7SwkKZVGdyk/q+ygLihtfzpT0ABfW1/0H9QZXxDqdGvLeiVBwd36I+gU1bgWHSj",
	"u7Jvo94QLIvz2p5XOa3cS2Q5yVBbJTWommNxi0uX9BBZaR+ttEwXMfDKYtAdd+uMdp/j8vDwkd3Waz5z",
	"RgsIaRC686PeycEBVFq0PxvjfNThBKBA0tO+ux5Z9vbD9bAa8lLmCCkTSYbKGpc8ywBz7symDGcsXkL0",
	"3uktPq3hQ0QR2mqILdCjs4l6BIslnapCo+SUDA/LQ6MAXw+/1YiMFM4yTjHpUyI4F1btXCAWVG8Ap88v",
	"BodH9lwUMtMcKWSXMMPnSNCzJGQhc3BAQh6CVDk4gO6vNNS3193hcJTIeIRixFSccoOxKRWODr8dOM3A",
	"DjvIZYLZME96vSdjYSH05uz5s1FIsr+FTM64gK8hGtnHR1aDnLD4NoJpJhfkj1eYy3lwE3nVLlDj6flZ",
	"p9+Zo3Ipkp3D4dHwkCK+BQpW8M5J5xFdonBPSkxiRI5z+nfmEigru9bKhc4rrs2pe6TfqFz5dUMh5plB",
	"BZMl0JBgJdUwFGb8ViLlwfnKDJ+eukpiX08zdemlId20zRmxffrgRIpWeaYReUvKBD2KDiKXw0i3fHRW",
	"b1vsytm4sdyQvNrIaL3Dg7LFyr9tuuktt2JQKC4VWfVfaYhqbv5o20J9FOCu+pb++9Y3qT6h8WKl0H9z",
	"WE8t9EkKVaLhhti+XiugOT48vKOqYbOaoSVdZ/9YSZXf+4cKkrRl0bZGnz+0+UxDlZWjKg3deM171geB",
	"C9QGplxpQ4U3jw+PtoGqOpxRo/CkrkIQbdeVh1+v7bF609DzhEYFmF+b5UhspuubtOaM1GZbzo7P5yN+",
	"oeSCpLpCUyphRd3BQVHlY59fva3pByHpeiwo7uHk60TJhUZlH9WQcIWxyZZWUDgAgw87QLdQMhldHPee",
	"WLmQ4By4GYucLa1h+m4JPtAK0fnVW/D8cfSeJx9GTmGJaDpBux+L6PzN5dpjwasbOa/HbyWWCEYxoWNp",
	"WY5j3k0+W0tGdZnuvmwNtXnq49V709BdJNKS9PqhiaHew75GxUefbQUt2fwtqO8eWGXOuKCrQ+7D3chd",
	"q9v78vTwFGekYDjttwzHt0ELH/qdOp44orCI0uKdkVMzcDc1dH3RzD9/RVe4mH0V9SGlYkAnLTKu7WXd",
	"s9QhoCjVzNHWWNCEX+kK+x0xaOgGGurDT68u+zBnijNhtFOtLSkN4YWYShVjAnPOxiK6cDjyZiFQvVHn",
	"VQVgNISzBPNCWuQgm4AJYBkJx8FMiorCPWU/PnzcRgLPabunvshgTddoO7vVI6NQRdsifx63JcpQ0OUj",
	"UcO+9Gj3S6t6TXrj8e43qnrJe2Gf2wyBnKDclfZ8KIbh8hr1iUOkEyaWUa+dSbfqfj+i+eyncfh5+Uhr",
	"zaoDQ6XxRa5aLXIFaN6Tuio/6/37QIMf0XgEyNEwn7WyiwVVoopUr1ZB/ZqpWyemvbkeCrmIT3jpZqV1",
	"EHDWqrRafA9IWPvikbHokk7fg7/JidWiTvVS/DYEd1j+UGgICvyQc7WhwDORjAXOUZiSZdkynB6heShz",
	"bJOrfoNNyfrZ0Pn4E5TbzRSKmhnx8SnwmwRxXg0bYu4PJ0cfgErsCz88ZOn0ZZ0QLCcRchXKp/UcPXrI",
	"9bzkFN+LEX1g8ptDeP3UF51bcewVYCcGkr7nE4FsaMXHxw+54iuhy6KQygexcma8D+unF2fPenut+T68",
	"8ZkUU65cKMGfWo15QcN638ky00yP3hfMpB9qTpM1BEE197bNT68uIaeq6JHXsCBngk9RU0VCcJlqnLnC",
	"AWvhsMDcvPY2hIOD83KS8fjggBJC3F574EPUEbm9YuK6zgMWjf7KE21YfEu12KggZgKmaOJ0LKq5go30",
	"BFx1fAhoOVDzJHgDY1awCc+4WbZx2KAl/PTq8uM5a39T7DggWf7uFwwW6FBSkVi1zK80gViWpihN6FXS",
	"3g7E/9q/Gcj9tJe5SIb2Nw7zAmcuTv6h7zxao7w4ti9sUoLDj9VeG+jwkSpDhfcOaQhAzrTtVlN9XaFc",
	"bx+kD8bCdpSn6seGouApmGnSTavimCp/B7Tg0ykm4AHqosxjQfYF+UurziMgRbasAuxhMdagYFxomJZZ",
	"Bi/+y9nL0Y/nl9AtRcZv0Zk/QRkaaN9zY2Xo9C39cIpH+CQ8lzIS7H8KgBMEB1ynY+FfHFlwusBJqxUj",
	"F8JyGELtNwFsD6RBNypRG4y6ij1NuGD1Dhv11jctYdkAavKzQHd1jL3/VAjWLA4X/Kgcyy445kghZ0uY",
	"IBRMGc6ye9p3HqGaqD+1Mt+ZegNLHHtRsVsNaaLlDhpWbLGajItNL9qcM5ftcn42hCuNiXemjYVP+KH0",
	"kZr7rkrpCxqT99cNFLI4ZZMMn1gulXgI6rGYSdBGMT5LTRBNqxGvLl4530fDARcN4alMlkFyKbYYCwuq",
	"JxA9c8gweBsyvigflNitZzwbtOzsBdfQwoHu0+h4H3feJ5LwLj/e47Zjl+rfmUlwH/o6PT8bWOnIMaBe",
	"yH5aZ34JzkkH2YvWgpgZvff/7VQXGWwKq19wch4kFnQjMqejEdW8lHk0iqzNjooqXliOY+HkFbg8uRBX",
	"Xsl/y5LCwiBmSi1BSJKcfa9MukirZlMcW6KfIGjM+cCN+8TTIJ8zUwMP1zDBlIsEolalIbpLbfyrW84n",
	"qY4tyt68Gna7vhfMboIqld1bqHZcyKK9qdRucUxejtECJ0WrvmeFajhPF+T8RB3PMW0qJVR8vtJvoLvS",
	"XbYjbGnS0ZQ6CgzquV3trqAXVD5IRziwGHICLFuwpa4cuwcHx4fHBwewSNGkqKw+axn9KoOL67FQPg+P",
	"jDqK99gdJhaHpqGpTiblbVmMci7MKFhpFj95bgVrIlGPhR05Q3ZrjRdKWsZ31DgmxiG8EVXSfLc+Hwor",
	"Z1xSwFhYRc8YSrlnIQGr1M0UNK7BrsK7uxhErqrsJOG6YCZOo7HoRn4FwwDCGxoh6vtdxykTArOeHczv",
	"JhnCOaoB3R+L7u//9r++PdQwY0Uffv+3//lolDo3fIFqcHYOYaEarKTw6SH+nrPymdALVHosHh//YLc8",
	"R5ZZUAlpqL8OZWVSiQVN2RvCqVvzwKoQyRMoxSST8S0mMFnC5fmLZ4N2J32z/cQXClK197jYS759Xoec",
	"ax3wSR0pWrRFPyh0Hfn0QeGMqSSz6CqnFfWsyIYwWzuN+/iH3axivd1hk2P4y8CqRJaBw3g3WdefPpwf",
	"Dh81OIcVnzW+Qckq27nFX1HxKUcNEY0bwdcQhQkjYDNruRmISo1KrygnZTqNoHuqZlIc86Q/FrGktG9D",
	"6aG9Om33iTSdeemI/c+/vIWvqxp8ouA+UNicjMGooESZG+Zrs0YQrvhX6pd86DHyVfu6X49Ou+ydym1C",
	"nMJlBkys+jmVyirGPiVND+GpKg0OKJpmTWHMqSGFwrFQzOCAiBiJ3uHsPJB+xdm6j49/6LVRI7UA+EJE",
	"2GjFsBftHX7uuX1rg119SZ+EIwKf/vHAeuyDmZkeHbiGhGuSZJ+JJbxq5LW5NLS7KV86AzKQ/gZa2vv7",
	"GB+v5GyGCdjH76W1X+Bc3lJ9lKJaPp8nYClnUuaFo8mbkAu3aysDlmXbOZmbSwPLsiZv0dV8OjCyxrxR",
	"fyx8Umbom7JsMA0dwuSWe0wza+luIXNZmtMs2wukp1lW5bSBorUnD5AF4U8E56iW1XlUnfv8OVFLje2n",
	"4TKttwWj603MviDzqU/TQoXPaluBLjkz1ar1md3w1RnM6LwfIhnrRzR1CGdLaHpOd0Dc4/NdyM98VKmB",
	"+qvajA0R6pgxdL1/x8eBrfj1j7guvJEXlRyzBLoradkbwoU0VXKYm60rs8RbD4TPlPRmGSHXuiQFvpE5",
	"5hZap7QhXKDV7anQeCxCdoqimRI/i/KETpqXMFyh1d25gK67b1KcGjcX5pw0j7GotH+/u6GyE90kaKiH",
	"VASsTLgBCl23EfeFe+2tL1v5WFG+1qOvDun2vnMbeuqXFOiNpkObNPUzLhqn9Ql0s+JHdLTryqDVGAl3",
	"GtPdRR/OetxOICGTkbkSsJXSFnRYsDqtwxpdhWh9fq0TG9FYWBZicXRlSB9RoITMtsBODw6qGAhxH+6a",
	"F1A7ATByLCKnlFPioeYzUkqrcIvdda00YAjPscjk0sUCTcoMLJgwJLG4QfIq0yBlYdkZukpRJUtjVVjH",
	"EewP1Y7UHmxfRjddr+X7AimMH915rKUzRuWB2NuO7G9txLhdLfQ5kq5lgJe/nj1+tFL8oGGUF2R/Bo2o",
	"BrUmYft2f2v0dicNa9zHv1VZrGZbQWL38qfTwfE33xJJey9VH5oWan8sgsVJJFexgbCAftAYm7qiF2GV",
	"qmllXUPX7DZVK14pd31Xz/Jtr+/SP+16yjwkgHrx94I63icwsqyD/ohbIRcijO7SNpPw0+UhUDuRQTA2",
	"xoK4jn3SiVo4OHh8eEglUu4QqvaIDuROzj8BBkbKgU6lMhUU7PYCs1sbpHJLFDLj8TJqZzC1mtUvxmVa",
	"6mK/gCW8My0sOEd8q8zPmxwWjD4/OHRZi/1Q5yAPxQ7OHC6N3LcakhHhbY0aKcV1gey2wqnPZA0/c/QD",
	"rEH7Tn5baWypurKV93GXpdQ69+932Ta+u+4XVMH8DG35bKjmPEbLUcrCwvCbO/0an2vaU0iwQJGgiJfQ",
	"ff7UHic1EyZHeSIXYt1LwedIHZssqmEN1A6+HtihUysKozxJba1sqzWX5bizwm3vaq1audF/nFqt+7W1",
	"a7Rp3l2xdc8eYVt6zLThoD/GgmojphCw5h9RReUxN6wBur6wq9awNxR5rXDfv9QotWorLWoA/MvIy81W",
	"zQ9cWtREqhYFk74m0aglepjshYfNrv2rdzjK0FIMuhv9qycyWUbwf//PZmfrXMqk/Y7red27Z+5t0Nbr",
	"2L1sReAW7t1SKNVWNLSB3F++AuiL1/M0AQZdXpVYbSP/bbrF3dA5fDDye+vcao7hfwrYH4qQfg7fkINu",
	"vvpcGkXMqc5dUEM08sXckypeoolTa2PuQRYbWsnn/07kNXUEiNNN9Dm3l/+4suNhkTeYSP9/IvEfQRLd",
	"j0rOXb5stvSQ31uK5Diqd7LWW1Pvfq6VzkM3WvV2hucvLp/1gSf0T9Trw3rd/XAsQl2u604UUTd1xWPX",
	"GsxdpEraqmcYdCOWZVFvlUZgn/naN9OGU5dOtapcrLc9arYFdz2Vh2NxEb56ETV2fGJfPJEL0eo9sbrn",
	"zw0AtTOZ3Z0wao3fKDxZZc7QL7f+/2yF8dm51UaX8XbCXx2wM3C+DlhJ2PNgGvCnmUUNvG74W47qmlCT",
	"4Nv5wMhu/u5gv6t3rREvMDOSmSs6Yi7HJ3KpihEsmEGVM3VLDfKh6zqFwD+PBcsy3/Zp9YzPOY+6KzZj",
	"OUwvCuju846d2Wd5g0hQYQLWnqUEXVoPhWqYctmebGp8qliiZJHIhYDqNW3YciwCc1mV6A9hG9NYWMm7",
	"lWtY0JxmWQOvLrCtoLa1wcoKEG67obEKfWPAZVcEsPtPC7TRpwN95/PVbd2P8OpN7Vo/P+x82vR1IXLe",
	"+y25GMUfkeDsqRLwm3RmV90H6btekgimz5OsjvG+tEc54SQPthLfCkf74GpbqOtishfGwmljC2PBE+rL",
	"K2bh0yo1fZ2+Wu2V+l69MwWFN7jxJWEZsls9FqvU4i1kUaeJdpL4Ikr7PwrNX9e/CqL+GDj/D1CsQZdx",
	"2vxmitPRuPZI5tPFG5QwENIMSCO/ry+FSNUajY0pnehpdw+0EaYs9GgVZGpViy+wkMroRirytq8icA3O",
	"/74MsvkHcB9K8AoyUm/UGBNLQH2va+fWroQFF/oE9uiNPxb7NceHVW/8korwqv74fdeIeiw2vt4Ad3+8",
	"QZRZ1myuH/nu+tFYqFKsNwBwlQLNpvseDlvqYFZfqfiCFL2apAWV3YcbHPW6b2JU36P+w8mrzbWG73d0",
	"WZJzUUd/WRDS0/Bq3q6duNzXBOfQnXMGbxXDKb+1o1ANN7VC1SejESv40KW6DSnxIJWUJLHhWaSiekJN",
	"qrlqDnQyGlUvn3x/+P0hVQb65b4PgsHHs+zg/goFE+u/XRVP7UqT0ms3LAxqP+kLxc0r9K3i2gVtpIuB",
	"XH/4fwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
