// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AccessTokenTokenType.
const (
	AccessTokenTokenTypeBearer AccessTokenTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AccessTokenTokenType enum.
func (e AccessTokenTokenType) Valid() bool {
	switch e {
	case AccessTokenTokenTypeBearer:
		return true
	default:
		return false
	}
}

// Defines values for AssetKind.
const (
	AssetKindAudio AssetKind = "audio"
	AssetKindImage AssetKind = "image"
	AssetKindVideo AssetKind = "video"
)

// Valid indicates whether the value is a known member of the AssetKind enum.
func (e AssetKind) Valid() bool {
	switch e {
	case AssetKindAudio:
		return true
	case AssetKindImage:
		return true
	case AssetKindVideo:
		return true
	default:
		return false
	}
}

// Defines values for AssetStatus.
const (
	AssetStatusFailed     AssetStatus = "failed"
	AssetStatusProcessing AssetStatus = "processing"
	AssetStatusReady      AssetStatus = "ready"
	AssetStatusUploaded   AssetStatus = "uploaded"
)

// Valid indicates whether the value is a known member of the AssetStatus enum.
func (e AssetStatus) Valid() bool {
	switch e {
	case AssetStatusFailed:
		return true
	case AssetStatusProcessing:
		return true
	case AssetStatusReady:
		return true
	case AssetStatusUploaded:
		return true
	default:
		return false
	}
}

// Defines values for AssetUploadSessionUploadMethod.
const (
	PUT AssetUploadSessionUploadMethod = "PUT"
)

// Valid indicates whether the value is a known member of the AssetUploadSessionUploadMethod enum.
func (e AssetUploadSessionUploadMethod) Valid() bool {
	switch e {
	case PUT:
		return true
	default:
		return false
	}
}

// Defines values for ContinueItemModule.
const (
	Comic ContinueItemModule = "comic"
	Media ContinueItemModule = "media"
	Movie ContinueItemModule = "movie"
	Music ContinueItemModule = "music"
	Story ContinueItemModule = "story"
)

// Valid indicates whether the value is a known member of the ContinueItemModule enum.
func (e ContinueItemModule) Valid() bool {
	switch e {
	case Comic:
		return true
	case Media:
		return true
	case Movie:
		return true
	case Music:
		return true
	case Story:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusOk       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for LoginResponseTokenType.
const (
	LoginResponseTokenTypeBearer LoginResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the LoginResponseTokenType enum.
func (e LoginResponseTokenType) Valid() bool {
	switch e {
	case LoginResponseTokenTypeBearer:
		return true
	default:
		return false
	}
}

// Defines values for OpsBackupRunStatus.
const (
	OpsBackupRunStatusFailed  OpsBackupRunStatus = "failed"
	OpsBackupRunStatusOk      OpsBackupRunStatus = "ok"
	OpsBackupRunStatusRunning OpsBackupRunStatus = "running"
)

// Valid indicates whether the value is a known member of the OpsBackupRunStatus enum.
func (e OpsBackupRunStatus) Valid() bool {
	switch e {
	case OpsBackupRunStatusFailed:
		return true
	case OpsBackupRunStatusOk:
		return true
	case OpsBackupRunStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for OpsStatusState.
const (
	OpsStatusStateFailed OpsStatusState = "failed"
	OpsStatusStateOk     OpsStatusState = "ok"
	OpsStatusStateStale  OpsStatusState = "stale"
)

// Valid indicates whether the value is a known member of the OpsStatusState enum.
func (e OpsStatusState) Valid() bool {
	switch e {
	case OpsStatusStateFailed:
		return true
	case OpsStatusStateOk:
		return true
	case OpsStatusStateStale:
		return true
	default:
		return false
	}
}

// Defines values for TenantContextKind.
const (
	Household TenantContextKind = "household"
	Org       TenantContextKind = "org"
)

// Valid indicates whether the value is a known member of the TenantContextKind enum.
func (e TenantContextKind) Valid() bool {
	switch e {
	case Household:
		return true
	case Org:
		return true
	default:
		return false
	}
}

// Defines values for ListAssetsParamsKind.
const (
	ListAssetsParamsKindAudio ListAssetsParamsKind = "audio"
	ListAssetsParamsKindImage ListAssetsParamsKind = "image"
	ListAssetsParamsKindVideo ListAssetsParamsKind = "video"
)

// Valid indicates whether the value is a known member of the ListAssetsParamsKind enum.
func (e ListAssetsParamsKind) Valid() bool {
	switch e {
	case ListAssetsParamsKindAudio:
		return true
	case ListAssetsParamsKindImage:
		return true
	case ListAssetsParamsKindVideo:
		return true
	default:
		return false
	}
}

// Defines values for ListAssetsParamsStatus.
const (
	ListAssetsParamsStatusFailed     ListAssetsParamsStatus = "failed"
	ListAssetsParamsStatusProcessing ListAssetsParamsStatus = "processing"
	ListAssetsParamsStatusReady      ListAssetsParamsStatus = "ready"
)

// Valid indicates whether the value is a known member of the ListAssetsParamsStatus enum.
func (e ListAssetsParamsStatus) Valid() bool {
	switch e {
	case ListAssetsParamsStatusFailed:
		return true
	case ListAssetsParamsStatusProcessing:
		return true
	case ListAssetsParamsStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for CompleteAssetUpload202JSONResponseBodyStatus.
const (
	CompleteAssetUpload202JSONResponseBodyStatusProcessing CompleteAssetUpload202JSONResponseBodyStatus = "processing"
)

// Valid indicates whether the value is a known member of the CompleteAssetUpload202JSONResponseBodyStatus enum.
func (e CompleteAssetUpload202JSONResponseBodyStatus) Valid() bool {
	switch e {
	case CompleteAssetUpload202JSONResponseBodyStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for GetAssetVariantParamsVariant.
const (
	Medium GetAssetVariantParamsVariant = "medium"
	Poster GetAssetVariantParamsVariant = "poster"
	Thumb  GetAssetVariantParamsVariant = "thumb"
)

// Valid indicates whether the value is a known member of the GetAssetVariantParamsVariant enum.
func (e GetAssetVariantParamsVariant) Valid() bool {
	switch e {
	case Medium:
		return true
	case Poster:
		return true
	case Thumb:
		return true
	default:
		return false
	}
}

// Defines values for ForgotPassword202JSONResponseBodyStatus.
const (
	Accepted ForgotPassword202JSONResponseBodyStatus = "accepted"
)

// Valid indicates whether the value is a known member of the ForgotPassword202JSONResponseBodyStatus enum.
func (e ForgotPassword202JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	default:
		return false
	}
}

// Defines values for Register201JSONResponseBodyStatus.
const (
	Registered Register201JSONResponseBodyStatus = "registered"
)

// Valid indicates whether the value is a known member of the Register201JSONResponseBodyStatus enum.
func (e Register201JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Registered:
		return true
	default:
		return false
	}
}

// Defines values for ResetPassword200JSONResponseBodyStatus.
const (
	PasswordUpdated ResetPassword200JSONResponseBodyStatus = "password_updated"
)

// Valid indicates whether the value is a known member of the ResetPassword200JSONResponseBodyStatus enum.
func (e ResetPassword200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case PasswordUpdated:
		return true
	default:
		return false
	}
}

// Defines values for ListNotificationsParamsStatus.
const (
	All    ListNotificationsParamsStatus = "all"
	Unread ListNotificationsParamsStatus = "unread"
)

// Valid indicates whether the value is a known member of the ListNotificationsParamsStatus enum.
func (e ListNotificationsParamsStatus) Valid() bool {
	switch e {
	case All:
		return true
	case Unread:
		return true
	default:
		return false
	}
}

// AccessToken defines model for AccessToken.
type AccessToken struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn seconds until expiry
	ExpiresIn int                  `json:"expires_in"`
	TokenType AccessTokenTokenType `json:"token_type"`
}

// AccessTokenTokenType defines model for AccessToken.TokenType.
type AccessTokenTokenType string

// Asset defines model for Asset.
type Asset struct {
	CreatedAt  time.Time `json:"createdAt"`
	DurationMs *int      `json:"durationMs,omitempty"`

	// Error Failure reason; present when `status` is `failed`.
	Error  *string `json:"error,omitempty"`
	Height *int    `json:"height,omitempty"`

	// HlsUrl Master playlist URL; present once `status` is `ready`.
	HlsUrl    *string            `json:"hlsUrl,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Kind      AssetKind          `json:"kind"`
	MimeType  string             `json:"mimeType"`
	SizeBytes int64              `json:"sizeBytes"`
	Status    AssetStatus        `json:"status"`
	Width     *int               `json:"width,omitempty"`
}

// AssetKind defines model for AssetKind.
type AssetKind string

// AssetStatus defines model for AssetStatus.
type AssetStatus string

// AssetUploadSession defines model for AssetUploadSession.
type AssetUploadSession struct {
	Asset Asset `json:"asset"`

	// Upload Presigned request the client performs to store the original.
	Upload struct {
		Headers *map[string]string             `json:"headers,omitempty"`
		Method  AssetUploadSessionUploadMethod `json:"method"`
		Url     string                         `json:"url"`
	} `json:"upload"`
}

// AssetUploadSessionUploadMethod defines model for AssetUploadSession.Upload.Method.
type AssetUploadSessionUploadMethod string

// ContinueItem One "continue watching / reading / listening" entry for the cross-domain
// `/continue` rail [D-20]. Aggregated from each vertical's progress table.
type ContinueItem struct {
	Href      string             `json:"href"`
	Module    ContinueItemModule `json:"module"`
	PosterUrl *string            `json:"poster_url,omitempty"`

	// ProgressPct Fractional completion 0..100.
	ProgressPct int                `json:"progress_pct"`
	RefId       openapi_types.UUID `json:"ref_id"`
	Title       string             `json:"title"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// ContinueItemModule defines model for ContinueItem.Module.
type ContinueItemModule string

// CreateAssetRequest defines model for CreateAssetRequest.
type CreateAssetRequest struct {
	ContentType *string `json:"contentType,omitempty"`
	Filename    string  `json:"filename"`
	SizeBytes   int64   `json:"sizeBytes"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	AvatarUrl   *string             `json:"avatarUrl,omitempty"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`

	// Roles Role codes (e.g. ["user","creator"]). Frontend uses these to render UI affordances; the server is the authority on perm checks.
	Roles []string `json:"roles"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ForgotPasswordRequest defines model for ForgotPasswordRequest.
type ForgotPasswordRequest struct {
	Email openapi_types.Email `json:"email"`
}

// Health defines model for Health.
type Health struct {
	Cache  *bool        `json:"cache,omitempty"`
	Db     *bool        `json:"db,omitempty"`
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// JournalEntry defines model for JournalEntry.
type JournalEntry struct {
	AssetIds   []openapi_types.UUID `json:"asset_ids"`
	BodyMd     string               `json:"body_md"`
	CreatedAt  time.Time            `json:"created_at"`
	Id         openapi_types.UUID   `json:"id"`
	Mood       *string              `json:"mood,omitempty"`
	OccurredAt time.Time            `json:"occurred_at"`
	UpdatedAt  time.Time            `json:"updated_at"`
}

// JournalEntryWrite Create requires body_md; PATCH accepts any subset of the fields. `asset_ids`
// is rejected with 422 `journal/invalid-asset` until photo attachments (P1.5).
type JournalEntryWrite struct {
	BodyMd *string `json:"body_md,omitempty"`
	Mood   *string `json:"mood,omitempty"`

	// OccurredAt Optional; defaults to now. Backdating and future-dating are allowed.
	OccurredAt *time.Time `json:"occurred_at,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`

	// Remember Persist the session (durable refresh cookie) vs a session cookie.
	Remember *bool `json:"remember,omitempty"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn seconds until expiry
	ExpiresIn int                    `json:"expires_in"`
	TokenType LoginResponseTokenType `json:"token_type"`
	User      struct {
		DisplayName string              `json:"display_name"`
		Email       openapi_types.Email `json:"email"`
		Id          openapi_types.UUID  `json:"id"`
		Roles       []string            `json:"roles"`
	} `json:"user"`
}

// LoginResponseTokenType defines model for LoginResponse.TokenType.
type LoginResponseTokenType string

// Money Exact monetary amount [D-14/D-15]. `amount` is a decimal string to avoid float error.
type Money struct {
	// Amount Decimal string, e.g. "1234.56" (numeric(20,8) at rest).
	Amount string `json:"amount"`

	// Currency ISO 4217 code, e.g. "USD".
	Currency string `json:"currency"`
}

// Notification defines model for Notification.
type Notification struct {
	Body      *string   `json:"body,omitempty"`
	CreatedAt time.Time `json:"created_at"`

	// Data Target ids / links — e.g. `href` for the bell's click-through.
	Data map[string]interface{} `json:"data"`
	Id   openapi_types.UUID     `json:"id"`

	// ReadAt When the notification was marked read; null while unread.
	ReadAt *time.Time `json:"read_at"`
	Title  string     `json:"title"`

	// Type Open type registry (e.g. `media.asset_ready`). See notify/README.md.
	Type string `json:"type"`
}

// NotificationList defines model for NotificationList.
type NotificationList struct {
	Items []Notification `json:"items"`

	// NextCursor Keyset cursor for the next page; absent/null on the last page.
	NextCursor *string `json:"next_cursor,omitempty"`

	// UnreadCount Unread badge count for the bell.
	UnreadCount int `json:"unread_count"`
}

// OpsBackupRun One row of the backup-run ledger (`ops_backup_runs`).
type OpsBackupRun struct {
	Error      *string            `json:"error,omitempty"`
	FinishedAt *time.Time         `json:"finished_at,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	SizeBytes  *int64             `json:"size_bytes,omitempty"`
	StartedAt  time.Time          `json:"started_at"`
	Status     OpsBackupRunStatus `json:"status"`
	StorageKey *string            `json:"storage_key,omitempty"`
}

// OpsBackupRunStatus defines model for OpsBackupRun.Status.
type OpsBackupRunStatus string

// OpsStatus Freshness sentinel for the nightly Postgres backup (P0.5). `last_success_at`
// and `hours_since_success` are both null when a backup has never succeeded.
type OpsStatus struct {
	// HoursSinceSuccess Hours since the last success; null if none.
	HoursSinceSuccess *float32 `json:"hours_since_success,omitempty"`

	// LastRun The most recently started run of any status; null if none.
	LastRun *OpsBackupRun `json:"last_run,omitempty"`

	// LastSuccessAt Completion time of the most recent successful run; null if none.
	LastSuccessAt *time.Time `json:"last_success_at,omitempty"`

	// State `failed` (most recent completed run failed) → `stale` (no success within
	// 26 h, incl. never-ran) → `ok`. A running run never changes state.
	State OpsStatusState `json:"state"`
}

// OpsStatusState `failed` (most recent completed run failed) → `stale` (no success within
// 26 h, incl. never-ran) → `ok`. A running run never changes state.
type OpsStatusState string

// PaginatedResult Cursor-paginated envelope. Concrete endpoints override `items` with their
// element type (OpenAPI has no generics — compose with `allOf` + an `items`
// override, or document the element type in the operation).
type PaginatedResult struct {
	Items []interface{} `json:"items"`

	// NextCursor Opaque cursor for the next page; null on the last page.
	NextCursor *string `json:"nextCursor,omitempty"`

	// Total Total count when cheap to compute; otherwise omitted.
	Total *int `json:"total,omitempty"`
}

// PlaybackProgress defines model for PlaybackProgress.
type PlaybackProgress struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	PositionMs  int64      `json:"position_ms"`

	// ProgressPct Fractional completion 0..100. Absent if duration is unknown.
	ProgressPct *int      `json:"progress_pct,omitempty"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Problem RFC 7807 problem detail, served as `application/problem+json`. `type` is a
// stable URI (also the i18n key); Portal adds the extensions below.
type Problem struct {
	// Code Portal-stable machine slug (e.g. `invalid_credentials`).
	Code *string `json:"code,omitempty"`

	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// EnrollmentUrl For MFA-enrollment (403) — where to enroll a second factor [D-28].
	EnrollmentUrl *string `json:"enrollment_url,omitempty"`

	// Instance URI reference identifying the specific occurrence.
	Instance *string `json:"instance,omitempty"`

	// RequiredAcr For step-up (403) — the ACR the caller must satisfy [D-27].
	RequiredAcr *string `json:"required_acr,omitempty"`

	// Status HTTP status code, repeated for convenience.
	Status int `json:"status"`

	// Title Short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type Stable problem-type URI (i18n key).
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// DisplayName Optional; defaults to the email local-part.
	DisplayName *string             `json:"display_name,omitempty"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	NewPassword string `json:"new_password"`

	// Token The one-time reset token from the email link.
	Token string `json:"token"`
}

// TenantContext Resolved tenant scope for the `/t/{tenant}/…` prefix [D-23]. Multi-tenancy
// is deferred to Phase 1; v1 runs single-tenant (`me`).
type TenantContext struct {
	Kind     *TenantContextKind `json:"kind,omitempty"`
	Slug     string             `json:"slug"`
	TenantId openapi_types.UUID `json:"tenantId"`
}

// TenantContextKind defines model for TenantContext.Kind.
type TenantContextKind string

// UnreadCount defines model for UnreadCount.
type UnreadCount struct {
	UnreadCount int `json:"unread_count"`
}

// User defines model for User.
type User struct {
	AvatarUrl   *string             `json:"avatarUrl,omitempty"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
}

// AssetID defines model for AssetID.
type AssetID = openapi_types.UUID

// TenantSlug defines model for TenantSlug.
type TenantSlug = string

// BadRequest RFC 7807 problem detail, served as `application/problem+json`. `type` is a
// stable URI (also the i18n key); Portal adds the extensions below.
type BadRequest = Problem

// Forbidden RFC 7807 problem detail, served as `application/problem+json`. `type` is a
// stable URI (also the i18n key); Portal adds the extensions below.
type Forbidden = Problem

// NotFound RFC 7807 problem detail, served as `application/problem+json`. `type` is a
// stable URI (also the i18n key); Portal adds the extensions below.
type NotFound = Problem

// TooManyRequests RFC 7807 problem detail, served as `application/problem+json`. `type` is a
// stable URI (also the i18n key); Portal adds the extensions below.
type TooManyRequests = Problem

// Unauthorized RFC 7807 problem detail, served as `application/problem+json`. `type` is a
// stable URI (also the i18n key); Portal adds the extensions below.
type Unauthorized = Problem

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListAssetsParams defines parameters for ListAssets.
type ListAssetsParams struct {
	// Kind Filter by asset kind.
	Kind *ListAssetsParamsKind `form:"kind,omitempty" json:"kind,omitempty"`

	// Status Filter by status; `processing` includes still-`uploading` sessions.
	Status *ListAssetsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Cursor Opaque keyset cursor from a prior page's `next_cursor`.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAssetsParamsKind defines parameters for ListAssets.
type ListAssetsParamsKind string

// ListAssetsParamsStatus defines parameters for ListAssets.
type ListAssetsParamsStatus string

// CompleteAssetUpload202JSONResponseBodyStatus defines parameters for CompleteAssetUpload.
type CompleteAssetUpload202JSONResponseBodyStatus string

// PutAssetProgressJSONBody defines parameters for PutAssetProgress.
type PutAssetProgressJSONBody struct {
	PositionMs int `json:"position_ms"`
}

// GetAssetVariantParamsVariant defines parameters for GetAssetVariant.
type GetAssetVariantParamsVariant string

// ForgotPassword202JSONResponseBodyStatus defines parameters for ForgotPassword.
type ForgotPassword202JSONResponseBodyStatus string

// RefreshTokenJSONBody defines parameters for RefreshToken.
type RefreshTokenJSONBody struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// Register201JSONResponseBodyStatus defines parameters for Register.
type Register201JSONResponseBodyStatus string

// ResetPassword200JSONResponseBodyStatus defines parameters for ResetPassword.
type ResetPassword200JSONResponseBodyStatus string

// GetContinueItemsParams defines parameters for GetContinueItems.
type GetContinueItemsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListJournalEntriesParams defines parameters for ListJournalEntries.
type ListJournalEntriesParams struct {
	// Cursor Opaque keyset cursor from a prior page's next_cursor.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListNotificationsParams defines parameters for ListNotifications.
type ListNotificationsParams struct {
	Status *ListNotificationsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Cursor Opaque keyset cursor from a prior page's `next_cursor`.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListNotificationsParamsStatus defines parameters for ListNotifications.
type ListNotificationsParamsStatus string

// MarkAllNotificationsReadParams defines parameters for MarkAllNotificationsRead.
type MarkAllNotificationsReadParams struct {
	// Before Keyset watermark cursor; absent marks all unread read.
	Before *string `form:"before,omitempty" json:"before,omitempty"`
}

// CreateAssetUploadJSONRequestBody defines body for CreateAssetUpload for application/json ContentType.
type CreateAssetUploadJSONRequestBody = CreateAssetRequest

// PutAssetProgressJSONRequestBody defines body for PutAssetProgress for application/json ContentType.
type PutAssetProgressJSONRequestBody PutAssetProgressJSONBody

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = ForgotPasswordRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody RefreshTokenJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// CreateJournalEntryJSONRequestBody defines body for CreateJournalEntry for application/json ContentType.
type CreateJournalEntryJSONRequestBody = JournalEntryWrite

// PatchJournalEntryJSONRequestBody defines body for PatchJournalEntry for application/json ContentType.
type PatchJournalEntryJSONRequestBody = JournalEntryWrite

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["enrollment_url"]; found {
		err = json.Unmarshal(raw, &a.EnrollmentUrl)
		if err != nil {
			return fmt.Errorf("error reading 'enrollment_url': %w", err)
		}
		delete(object, "enrollment_url")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["required_acr"]; found {
		err = json.Unmarshal(raw, &a.RequiredAcr)
		if err != nil {
			return fmt.Errorf("error reading 'required_acr': %w", err)
		}
		delete(object, "required_acr")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.EnrollmentUrl != nil {
		object["enrollment_url"], err = json.Marshal(a.EnrollmentUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'enrollment_url': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.RequiredAcr != nil {
		object["required_acr"], err = json.Marshal(a.RequiredAcr)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'required_acr': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List the caller's assets
	// (GET /assets)
	ListAssets(w http.ResponseWriter, r *http.Request, params ListAssetsParams)
	// Begin a media upload
	// (POST /assets)
	CreateAssetUpload(w http.ResponseWriter, r *http.Request)
	// Delete an asset (owner, or `assets:delete:any`)
	// (DELETE /assets/{id})
	DeleteAsset(w http.ResponseWriter, r *http.Request, id AssetID)
	// Get asset metadata
	// (GET /assets/{id})
	GetAsset(w http.ResponseWriter, r *http.Request, id AssetID)
	// Confirm the upload and enqueue processing
	// (POST /assets/{id}/complete)
	CompleteAssetUpload(w http.ResponseWriter, r *http.Request, id AssetID)
	// Public HLS proxy (manifest + segments)
	// (GET /assets/{id}/hls/{path})
	GetAssetHLS(w http.ResponseWriter, r *http.Request, id AssetID, path string)
	// Download the original file (owner-only)
	// (GET /assets/{id}/original)
	DownloadAssetOriginal(w http.ResponseWriter, r *http.Request, id AssetID)
	// Fetch playback progress
	// (GET /assets/{id}/progress)
	GetAssetProgress(w http.ResponseWriter, r *http.Request, id AssetID)
	// Save playback progress
	// (PUT /assets/{id}/progress)
	PutAssetProgress(w http.ResponseWriter, r *http.Request, id AssetID)
	// API-proxied upload of the original bytes (dev path)
	// (PUT /assets/{id}/source)
	UploadAssetSource(w http.ResponseWriter, r *http.Request, id AssetID)
	// Stream a derived variant (public-ish)
	// (GET /assets/{id}/variants/{variant})
	GetAssetVariant(w http.ResponseWriter, r *http.Request, id AssetID, variant GetAssetVariantParamsVariant)
	// Request a password-reset email (SPEC-04 P0.3)
	// (POST /auth/forgot-password)
	ForgotPassword(w http.ResponseWriter, r *http.Request)
	// Local password login
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Revoke current session and bump token_version
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Revoke every session for the current user
	// (POST /auth/logout-all)
	LogoutAll(w http.ResponseWriter, r *http.Request)
	// Get the currently authenticated user
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Rotate refresh token, mint new access token
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Create a local account
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// Consume a reset token and set a new password (SPEC-04 P0.3)
	// (POST /auth/reset-password)
	ResetPassword(w http.ResponseWriter, r *http.Request)
	// List active progress items across modules (SPEC-07)
	// (GET /continue)
	GetContinueItems(w http.ResponseWriter, r *http.Request, params GetContinueItemsParams)
	// Liveness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List the caller's journal entries (newest occurred_at first)
	// (GET /journal/entries)
	ListJournalEntries(w http.ResponseWriter, r *http.Request, params ListJournalEntriesParams)
	// Create a journal entry
	// (POST /journal/entries)
	CreateJournalEntry(w http.ResponseWriter, r *http.Request)
	// Delete a journal entry (idempotent)
	// (DELETE /journal/entries/{id})
	DeleteJournalEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Fetch one journal entry
	// (GET /journal/entries/{id})
	GetJournalEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Partially update a journal entry
	// (PATCH /journal/entries/{id})
	PatchJournalEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List the caller's notifications (SPEC-04 P0.1)
	// (GET /me/notifications)
	ListNotifications(w http.ResponseWriter, r *http.Request, params ListNotificationsParams)
	// Mark all notifications read, optionally up to a watermark
	// (POST /me/notifications/read-all)
	MarkAllNotificationsRead(w http.ResponseWriter, r *http.Request, params MarkAllNotificationsReadParams)
	// Mark one notification read (idempotent)
	// (POST /me/notifications/{id}/read)
	MarkNotificationRead(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Backup freshness sentinel (admin)
	// (GET /ops/status)
	GetOpsStatus(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List the caller's assets
// (GET /assets)
func (_ Unimplemented) ListAssets(w http.ResponseWriter, r *http.Request, params ListAssetsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Begin a media upload
// (POST /assets)
func (_ Unimplemented) CreateAssetUpload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an asset (owner, or `assets:delete:any`)
// (DELETE /assets/{id})
func (_ Unimplemented) DeleteAsset(w http.ResponseWriter, r *http.Request, id AssetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get asset metadata
// (GET /assets/{id})
func (_ Unimplemented) GetAsset(w http.ResponseWriter, r *http.Request, id AssetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Confirm the upload and enqueue processing
// (POST /assets/{id}/complete)
func (_ Unimplemented) CompleteAssetUpload(w http.ResponseWriter, r *http.Request, id AssetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Public HLS proxy (manifest + segments)
// (GET /assets/{id}/hls/{path})
func (_ Unimplemented) GetAssetHLS(w http.ResponseWriter, r *http.Request, id AssetID, path string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download the original file (owner-only)
// (GET /assets/{id}/original)
func (_ Unimplemented) DownloadAssetOriginal(w http.ResponseWriter, r *http.Request, id AssetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch playback progress
// (GET /assets/{id}/progress)
func (_ Unimplemented) GetAssetProgress(w http.ResponseWriter, r *http.Request, id AssetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Save playback progress
// (PUT /assets/{id}/progress)
func (_ Unimplemented) PutAssetProgress(w http.ResponseWriter, r *http.Request, id AssetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// API-proxied upload of the original bytes (dev path)
// (PUT /assets/{id}/source)
func (_ Unimplemented) UploadAssetSource(w http.ResponseWriter, r *http.Request, id AssetID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream a derived variant (public-ish)
// (GET /assets/{id}/variants/{variant})
func (_ Unimplemented) GetAssetVariant(w http.ResponseWriter, r *http.Request, id AssetID, variant GetAssetVariantParamsVariant) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a password-reset email (SPEC-04 P0.3)
// (POST /auth/forgot-password)
func (_ Unimplemented) ForgotPassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Local password login
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke current session and bump token_version
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke every session for the current user
// (POST /auth/logout-all)
func (_ Unimplemented) LogoutAll(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the currently authenticated user
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rotate refresh token, mint new access token
// (POST /auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a local account
// (POST /auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Consume a reset token and set a new password (SPEC-04 P0.3)
// (POST /auth/reset-password)
func (_ Unimplemented) ResetPassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List active progress items across modules (SPEC-07)
// (GET /continue)
func (_ Unimplemented) GetContinueItems(w http.ResponseWriter, r *http.Request, params GetContinueItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List the caller's journal entries (newest occurred_at first)
// (GET /journal/entries)
func (_ Unimplemented) ListJournalEntries(w http.ResponseWriter, r *http.Request, params ListJournalEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a journal entry
// (POST /journal/entries)
func (_ Unimplemented) CreateJournalEntry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a journal entry (idempotent)
// (DELETE /journal/entries/{id})
func (_ Unimplemented) DeleteJournalEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch one journal entry
// (GET /journal/entries/{id})
func (_ Unimplemented) GetJournalEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Partially update a journal entry
// (PATCH /journal/entries/{id})
func (_ Unimplemented) PatchJournalEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List the caller's notifications (SPEC-04 P0.1)
// (GET /me/notifications)
func (_ Unimplemented) ListNotifications(w http.ResponseWriter, r *http.Request, params ListNotificationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Mark all notifications read, optionally up to a watermark
// (POST /me/notifications/read-all)
func (_ Unimplemented) MarkAllNotificationsRead(w http.ResponseWriter, r *http.Request, params MarkAllNotificationsReadParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Mark one notification read (idempotent)
// (POST /me/notifications/{id}/read)
func (_ Unimplemented) MarkNotificationRead(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Backup freshness sentinel (admin)
// (GET /ops/status)
func (_ Unimplemented) GetOpsStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAssets operation middleware
func (siw *ServerInterfaceWrapper) ListAssets(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAssetsParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAssets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAssetUpload operation middleware
func (siw *ServerInterfaceWrapper) CreateAssetUpload(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAssetUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAsset operation middleware
func (siw *ServerInterfaceWrapper) DeleteAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAsset(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsset(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteAssetUpload operation middleware
func (siw *ServerInterfaceWrapper) CompleteAssetUpload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteAssetUpload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAssetHLS operation middleware
func (siw *ServerInterfaceWrapper) GetAssetHLS(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "path" -------------
	var path string

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetHLS(w, r, id, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadAssetOriginal operation middleware
func (siw *ServerInterfaceWrapper) DownloadAssetOriginal(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadAssetOriginal(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAssetProgress operation middleware
func (siw *ServerInterfaceWrapper) GetAssetProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetProgress(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutAssetProgress operation middleware
func (siw *ServerInterfaceWrapper) PutAssetProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAssetProgress(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadAssetSource operation middleware
func (siw *ServerInterfaceWrapper) UploadAssetSource(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadAssetSource(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAssetVariant operation middleware
func (siw *ServerInterfaceWrapper) GetAssetVariant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "variant" -------------
	var variant GetAssetVariantParamsVariant

	err = runtime.BindStyledParameterWithOptions("simple", "variant", chi.URLParam(r, "variant"), &variant, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "variant", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetVariant(w, r, id, variant)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ForgotPassword operation middleware
func (siw *ServerInterfaceWrapper) ForgotPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ForgotPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutAll operation middleware
func (siw *ServerInterfaceWrapper) LogoutAll(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutAll(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetContinueItems operation middleware
func (siw *ServerInterfaceWrapper) GetContinueItems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetContinueItemsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetContinueItems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListJournalEntries operation middleware
func (siw *ServerInterfaceWrapper) ListJournalEntries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListJournalEntriesParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListJournalEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) CreateJournalEntry(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJournalEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) DeleteJournalEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteJournalEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) GetJournalEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJournalEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) PatchJournalEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchJournalEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNotifications operation middleware
func (siw *ServerInterfaceWrapper) ListNotifications(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNotificationsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNotifications(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkAllNotificationsRead operation middleware
func (siw *ServerInterfaceWrapper) MarkAllNotificationsRead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params MarkAllNotificationsReadParams

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkAllNotificationsRead(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkNotificationRead operation middleware
func (siw *ServerInterfaceWrapper) MarkNotificationRead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkNotificationRead(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpsStatus operation middleware
func (siw *ServerInterfaceWrapper) GetOpsStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpsStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets", wrapper.ListAssets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/assets", wrapper.CreateAssetUpload)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/assets/{id}", wrapper.DeleteAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}", wrapper.GetAsset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/assets/{id}/complete", wrapper.CompleteAssetUpload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}/hls/{path}", wrapper.GetAssetHLS)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}/original", wrapper.DownloadAssetOriginal)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}/progress", wrapper.GetAssetProgress)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/assets/{id}/progress", wrapper.PutAssetProgress)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/assets/{id}/source", wrapper.UploadAssetSource)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}/variants/{variant}", wrapper.GetAssetVariant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/forgot-password", wrapper.ForgotPassword)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout-all", wrapper.LogoutAll)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/reset-password", wrapper.ResetPassword)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/continue", wrapper.GetContinueItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/journal/entries", wrapper.ListJournalEntries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/journal/entries", wrapper.CreateJournalEntry)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/journal/entries/{id}", wrapper.DeleteJournalEntry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/journal/entries/{id}", wrapper.GetJournalEntry)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/journal/entries/{id}", wrapper.PatchJournalEntry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/notifications", wrapper.ListNotifications)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/me/notifications/read-all", wrapper.MarkAllNotificationsRead)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/me/notifications/{id}/read", wrapper.MarkNotificationRead)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ops/status", wrapper.GetOpsStatus)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3ZbhvJluCvHPA2UKSKm2TXJqPRUHmp0r12WZDsWwOYHmUw85AZV5kRWRGRpHkNA/00QL8O5hNm5hfm",
	"fT6lvmQQJyKSmWRSpLzo1nT3k0QyM5YTZ9/ifSeWeSEFCqM7p+87BVMsR4OKPp1pjeb8if2Xi85pp2Am",
	"7fQ7guXYOe3wpNPvKPyt5AqTzqlRJfY7Ok4xZ/aNmVQ5M53TTlnSk2ZV2Le0UVzMOx8+9DuvUDBhrrJy",
	"bp9PUMeKF4ZLO5X7DXRWzmEmFZgUIRqZ0XtDP3wY/f6v/zuCQuGMvxtClGMEGjOMjaZHY5ZlqL7SE1Gg",
	"0lKwDHQsCxzCizIzfOBGASVLw8UcuIYEZ6gUJmAkXKRMIxxDVyNORPSn0RpII7dBPXILfCyFwXcm6j2C",
	"xTGoUmjQXMwz9DMMJ6LTbwOe+/lWAG4C7IN9WBdSaKTT+ZEll/hbidrYT7FdiaB/WVFkPGYWkqNCyWmG",
	"+dd/0xas72vD/5PCWee007q5C/eWm7R5MC9YZk8WE1B+8g/9zjOppjxJUNznSs5Kk6IwdnxM+jAtDWQs",
	"vtFQoMq51lwK6EoF2mAxKAsIkO7ZFf8izTNZiuQ+F3yJWpYqRhDSwIxmt1Qg5QsmVv4o9b0uiBmEjOfc",
	"wAgyGd/I0oBRvCiQlvZasNKkUvG/470C6oU9PTEHqYCLBct4ArHCxB42yzTxDj8Kcak4Rq1fyRuHfoWS",
	"BSrDHZEw+vHahF83iKrfwXcFV6ivudhmQhpjKRINpTA8A3pyteZkXBico7KD0PDX7vv3HRRl3jl90/kR",
	"mULVedvG+9Zk/6a5xsaKGiOvx5HTv2FMhEccenvXsUJLFGemwYgTZnBgeI7b3LjfSUpFp/mCBhBllrFp",
	"hoErbW8ZlZJqG2TPGM9KhaCQaSkeWQ6tURhYpigg0oaZUkeW30YzxjNMoqHlie2zrReXIp+n5rCFpZl+",
	"rbLtlb1g2qCCImOrjGsDry+fr5cnRYzN5SlkyYpWtxZkih+yWJ4cIP76nRvuuM9tNELH+xfuGEXOc3zl",
	"UWxrNM3/jj+ujDv+am4uzLcPWzHWbfWg+a/cox/6nSVPTHrIKWwgOAHAz+g3XttOffH9GuruxPe/eMgF",
	"OlvwBGWn32Flwu1fnrM5tpCdf/2q2noYoCwyyRK0qyqUtMRon7d7YIkleIequ0d8Te9fIcmcFh4UiHQv",
	"qO2IbjHb+HuhUPO5WAtep+hk3OJvgcoeurbaizZSIf0oFZ9zwbKh21htSSmyxCt5LEm4nYJlF41Htra6",
	"dRg5mlQ2TuLi9atWKJWOIDco6XauaN+p5tjGhU0eSuCroNeGO1ZX46LEc4P5NnhfCoQJSTj7DCyZiVMr",
	"g0aWlSXuP8s3UHAxn3QAhVGrSjWNldR6kMiccTER0SiME4FiPIM3TwYn47dDOJvPFc4tfsNMyRyQxSks",
	"LMxjln2loVByrlBrMJa6nPK4cXCEQi2nk8ukzBriJ8eEMwtCueCWyvJS85gIUZIYi2XO49bjKqRlldf+",
	"1PYyvLDq6yI2LRJBsdjhF1i0z9B+gPFweDweW8TM2Tue2xUfj8eWKwj3adzGtRTOrg9kr4abrJ1VloUV",
	"hMk1O1g6buCaB3W1nDDZBiT67rAaE7biJXE8ov+aPr8h0J3mFdh/gjNWZnbVdT1MxgbNQBuFLG8DyYxn",
	"6MyPTxYgGxCpRq6P07rXUikU5rVG0h1Ylr2cdU7f3M4a6ekP/U2YKJm5fzaUWpkhxDJBDV0czofwZtIp",
	"NapJpz9x0kWqSedtbwjPFEE1gVIjmY0aLf9UKBJU8Poc2GwmVcJEjPoRkblGtUBl9QP7ySvHZgVSkNEB",
	"cYrxjbZYzQ3mt7JRphRbbQHS7Wkbcm8/9DtP1xpXoZCsnkCSm8iStJ9xjlpb0dhiXDaXQSOsn287yWdS",
	"zaW5YFovpUp2Ii7mjDd5v/tmH425p9om/hlZ5rSQjV2zOK1vbSplhkyQbjtt/15vaQLypmONkbkidWCv",
	"5u4HaFvmn2WpBMueWjGxQyW45gl9qHBlP1Nr4E6/M5XJ6jpPWg/bK1J3YHMHq665dGJ/r2SQcWwJ/m6L",
	"+GT+TIsOoOnXYN1cUANEe7l0/Tx/VdzgNudxjDz4GTT4JTyCi7NXj38Ga+YVRgMTK9DlVKMBOSNGMuOY",
	"JXoIUbXUaCK4BoV2dkxgyU0KD09OIPqbW8bI28UDeiPyFmqRSiOBGcPiNLcsFLoXx8Nvem2KRA11cvbu",
	"OYq5JaqT8dhL4fDN8S3nX3vx+6237oocG+pY4XSGR+BlHam2Qi6H8COLbxJGfjsmEpiVplQ4CN8oBJZl",
	"colJw3a7HXu2Tvu5nHPx6Uyt3yk8g2w8XX3Z8oLCHPMpqoaYn7FM46aX5AKV5t4M0Oj9XdaMn2YWCWcK",
	"dQqxlDcce7DQwKqn3JfD9fQVT2zlwrVdvN0NK+eZPFyq190228K99BpC89uEa2u/X+/UYu5wMgfyukrL",
	"+EiJTqOGRTTW398p7TctId3wItV1ghdS4Gqbep6+Y7GBXAo0TK2A5bIUxlohxw9HTwbH37y1vIa+JGcH",
	"gwRjnrMM3KYsqbGF5AnMMskMkK9n24h0I2zP/qQxWB9IC5t0jk8ePBx+8+2kA11R5qh43D0Z97/vATOg",
	"UJsezcCMQWVH+a+Df3kzHvzw9uvuZDJ0//X+5Z/ajojYiIhb4HB+9RIenhx/R/pgtZDXV08mHW96BIb1",
	"oMG+Hux12bmt1+Zuo4xfpOEzr51vI7PlwJ9NcifMsN3WvOPAGxEWpuZogCeaLFtxo+H3f/0fDkaRtVyi",
	"yrqdYmat0zjj8c3ApEqW87TGPdYbPpSmkLVz/V9TFDSjqEEOlkxDztQNuT5Y8gisaIFlyjOEUtivdrL6",
	"vUJot5loKlurKZfsCleF5bBzro1aeSsjInN76CS4cx72hnCFfi+r0eXTsycvng7zZHiYAmOcbyyYlnTA",
	"a9A1sGQf7j3nbVKsYmjVP7ex6wYut6iiAt+Z67hUus0r/BdcWXXH/VyhlX0FCjbHR8CmGoUZ0cFKhwIZ",
	"0+7XgzzEDg+u43aO9Jp+hSlL5tY2tMywjtvD/Raug9HGPG1wf1loq6CUxWUp2r1MSi6D4jelJweqFJBh",
	"MkcF3UgW+tp9f61KoaPeNuOtfO97wTLjguv0dl7yuRza1vK/nu50Iez33GvD1F353rYJp0ohnPuWjLlb",
	"fLfaSMXmeH3jROgeONzq064tfQdSrL3Om+4x1KlArcFSABeYremDz1OTreBCajMng4LQAroXY6vUQ2RJ",
	"5FqXLnzETDQRViGOUlkqfa25iDH8GpFiPJUmDcwTBbAwYMo0CFygAnocE0xafY/b427v52f7ENBDazL2",
	"T3vOzWcgpLiNrkVJKvCHfoe2qBwpHaZXNgjww9stsZci5FJblSNGYcHrzw4sFcqZM8/osPYtNyxvfQIt",
	"NuHa5WlROBB+bQUBOLMys0vYnvTjiNZuoUV+hbAbdOtL8I5ZDwT3SA9+/2//nWJiGUbQFTIslKxRLibi",
	"5FtI+8BFnA0d+gwUE/41eRMN4Qw8MdKwDsPilIk5agKx93A3nC8032102+KCafdQXbA5F1ZEXqImK2rr",
	"bEgcDYrwHKBYYEZZIo+liBUaBBRJIbk1peUCleIJQkSyIHJGuUmRq4nADK3B7TSDrlUSzi7OHV1JmKOw",
	"2q7TrwhjNbq3I0LpCL4GJsK4ExFm6oNUkMi4dEOnCI1puJOTlkJJKrea+VtCfofofrxDcr8s2G8l3iK5",
	"P15kG2lYS5z2lf3aC2liU3GKrLAmiQVdafARSJOiWnKNIHNujDP17xqTJHi04k3GVpYxXnhnfps33pPL",
	"J4nVQmpS1a/zQ4O2nxBogTPSsCxfCZF+a/mV4kbIpRi2TvfJjrj6Dvc62EI+yJ2MmMtnj+G778ffgc9B",
	"gQQN41nfeeoTYBqiXakq0RAiuwpnAk+EpqAbvL48hy7LtCSU5sffC7jBVe8RXEhlMZMliXP/4zuDQnMp",
	"tFUi5bKN/IIrfsNzQyMN/IQ5i1Mu0OW6eWPCu/eua2kvThHcNvxowy1yuMyZGFhllSbBd0XGhDt3XWBs",
	"dXlLUyblGrwnTsTYOgUKJbPMMp4QEtxAPKngxbOzwfo56D4cP+gRv1umqCis4n4lL1QsRQIzFhupKDT6",
	"/duWPIttNdSekIhb4GmPTOEMaQvACWKzFTkyUlxvt7nNfdMFRL5msWrfc0gsW2/WTnf2+LKWggh5afUf",
	"ZrierWiz370d3q7Ibpzjq1cXXh/xXgyFBboQslQQS7FAwTfOrp6aFAzc5rBXqVSmD2kTS3SZ50ytgpYS",
	"iMqOOtwdj2jEI6eyNKfTjAkXSWnM6fDdjzogIUbUVhHZ/nPZ4DAbRvIt8ZhLMtdR7XTqbvoWD/FHExvI",
	"Gc8gkzHLBgVTpp2EPp/HuOam+v6wKNoe/+0latwfyBO4vP6kpflcthaBb5UY4UQKKLsYoCddikQNxFzc",
	"7PedhCy6xnrbtt1I4G0JI6OWmRUhPlWY0of3piIThT9420gzjlcUzGlJMN6RNAzdKMeoVZ272Uh9ksoa",
	"uqksNaYy22Hm+gTr7fOg2c6Tw7K1G0AOb/rR2+DrfC6Pg0Nmw72/4a7Zo6zt9bq8bg0XsAUzTL1uTT7a",
	"q555fvDLfYUaDogb0FpawwUa41Jxs7qyRrB3L1P26VnpYuXu07OwhD//+qrjk2gp/uMyVauRU2MKl5jL",
	"xUzuUmBI5GnMZoNUaiuQyAUKRcaM3SucXZwPJ2IiXlkdo7JjfPLE0ZFPhrayRpUmPTqqqItkXiyFsRrt",
	"cCKuXNqFNuVUQ/cn2aPAn33y1arAK1pYyISr/Bxkda1TrbihtfzpT0B5FNp+oP+gSqqHUqNfW9Arj45u",
	"0R9Bp6zAiehGtyU4R70hWBbntT2vclq5l8hymqG2SmpQNSfiBlcu1ySy0j5aa5kuUOOVxaA77tcZ7T4n",
	"5Xj8wG7rBZ973V9Ig9BdHPdOj46g0qL92RgXGggnAAWSnvbd25Flbz+8HVZDXskcIWUiyVBZm55nGWDO",
	"nbWa4ZzFK4jeO73FZ5N8iCgwXg2xA3p0NlGPYLGiU1VolJyRvWd5aBTg6+G3HpGRwlnGKSZ9yrXnwqqd",
	"S8SCSjrg7MnlYHxsz0UhM82RQlIPM3yBBD1LQhYyR0ck5CFIlaMj6L6hob592x0OR4mMRyhGTMUpNxib",
	"UuFo/O3AaQZ22EEuE8yGedLrPZoIC6GX508ej0Idww1kcs4FfA3RyD4+shqkNUQjmGVySWEQhblcBO+c",
	"V+0CNZ5dnHf6nQUql4XaGQ+Ph2MKtBcoWME7p50H9BVF2VJiEiOKV9C/c5ejWrkTrFzoPOfanLlH+o3i",
	"oDdbCjHPDCqYroCGBCuphqH25bcSKeXQF7/4DOB1ncBmJq/L4A0ZvW0+oN3TB99dtE7ljchJVSboUXQQ",
	"uTRR+skHxfWuxa59vFvLDfnBjaThWxxXO5wrN83oiOVWDArFpSJnylcaolp0Jdq1UB98ua2EqP++9U0q",
	"AWm8WCn034x3Zmget/hY3m7UKJ2Mx7cUjmwXjLRkSR0eoqpSqP9Qsam2ROXWoP+HNld1KGRzVKWhG284",
	"LfsgcInawIwrbai26eH4eBeoqsMZNWp76ioE0XZdeXjz1h6rNw09T2gU2fm1WY7E5rq+SZ9LvCtVyqdR",
	"Er9QcklSXaEplbCi7uioqFLeL16/qukHIa99Iijc5OTrVMmlRmUf1ZBwhbHJVlZQOACDj/ZAt1AyGV2e",
	"9B5ZuZDgAriZiJytrGH6bgU+vg3RxetX4Pnj6D1PPoycwhLRdIJ2PxHRxcurjceCdzByXo/fSiwRjGJC",
	"x9KyHMe8m3y2lgPsigl8ZSBq86NPEziYhm4jkZZc4w9NDPWBjQ0qPv5sK2gpmGhBfffAOmHJxbodco/3",
	"I3etNPLL08OPOCcFw2m/ZTi+LVr40O/U8cQRhUWUFu+MnJmB+1FD19cl/fNX9A0X86+iPqRUb+mkRca1",
	"/Vr3LHUIKEo1d7Q1ETThV7rCfkcMGrqBhvrw8/OrPiyY4kwY7VRrS0pDeCpmUsWYwIKziYguHY68XApU",
	"L9VFVWQZDeE8wbyQFjnIJmACWEbCcTCXoqJwT9kPxw/bSOAJbffM13Fs6BptZ7d+ZBQKlVvkz8O2/CRy",
	"3n8katiXHux/aV0SS2883P9GVZJ6J+xzmyGQE5S70p4PhY5cOqk+dYh0ysQq6rUz6Vbd7yc0n/00xp+X",
	"j7SWBTswVBpf5AoCI1fj5z2p6wq/3r8PNPgJjUeAHA3zyUL7WFAlqkj1ahXUL5i6cWLam+uhVo74hJdu",
	"VloHAWetSqvF94CEdZlPBePZRHRJp+/B3+TUalFneiV+G4I7LH8oNAQFfsi52lDgmUgmAhcoTMmybBVO",
	"j9A8VJK2yVW/waZk/WzofPIJyu125krNjPj4yoNtgriohg2pDvcnR++BSuwLP9xndfpVnRAsJxFynUFB",
	"6zl+cJ/recYpvhcj+sDkN2N48aOv67fi2CvATgwkfc8nAtnQik9O7nPFr4Uui0IqH8TKmfE+rJ+fnj/u",
	"HbTmu/DGx1LMuHKhBH9qNeYFDet9L8tMMz16XzCTfqg5TTYQBNXC2zY/P7+CnArPR17DgpwJPkNNhSDB",
	"Zapx7uo1rIXDAnPz2tsQjo4uymnG46MjysNxe+2BD1FH5PaKies6D1g0+itPtGHxDZW7o4KYCZihidOJ",
	"qOYKNtIjcA0IQkDLgZonwRsYs4JNecbNqo3DBi3h5+dXH89Z+9tixwHJ8ne/YLBAh5Jq86plfqUJxLI0",
	"RWlCO5j2jiv+0+H9Vu6mvSxEMrSfcZgXOHdx8g9959Ea5cWJfWGbEhx+rPfaQIePVBkqvHdIQwBypm23",
	"murrCuV6hyB9MBZ2ozwVnTYUBU/BTJNuWtUkVWlToAWfzTABD1AXZZ4Isi/IX1o1dwEpslUVYA+LsQYF",
	"40LDrMwyePpfzp+Nfrq4gm4pMn6DzvwJytBA+7Yma0Onb+mHUzzC5z66lJFg/1MAnCA44DqdCP/iyILT",
	"BU5arRi5FJbDEGq/DGC7Jw26UQDcYNRV7GnKBas3Mal3F2oJywZQk58Fuutj7P2nQrBhcbjgR+VYdsEx",
	"Rwo5W8EUoWDKcJbd0b7zCNVE/ZmV+c7UG1jiOIiKi1pC260WX5X59oe0/Lby89p1XtdIwaVH6U/A1i9m",
	"sj2z8pgE9JQk9RrobW7UsuW8LsrPel4f525sWjUbSY23tXO4JVmw3azZ56R82NY0xeOBZov7tnu+GOJc",
	"sQUehjebHMDxIzqnco8UV2y5ZjdcbPvRF5y5fLeL8yG81ph4d/pE+JQ/SiCrOfCrXOpgM3mP/UAhi1M2",
	"zfCR3UzieaieiLkEbRTj89QE5XQ94uvL58772XDBR0OwGBx0V8WWE2GZ5SOIHjuMHrwKOZ+UiE8Kl1c9",
	"tqS58xi4rkEOdF+ewj5RiH8EkVwZqf6dOQXuQk5nF+cDqx9zDKgX8h831Z8EF2SFHCRtg6I5eu//22sw",
	"MthWV3/F6UXQWaEbkUMtGlGxYZlHo8i16qFSQ5bjRDiNFVymbMgsWVsAVikJC4OYKbUCIUl37ntz0uVa",
	"aDbDiSX6KYLGnA/cuI88DfIFMzXwcA1TTLlIIGo1G6LbDMe/uuV8kvHYYu4tqmF3W3zB8UZQpX4nFqqd",
	"0ACpzQu3X7EhP+doidOi1eKzanU4T5fm8IlWnmPaVMOt+GJt4UB3bb3sRtjSpKMZtXIZ1LM7253BT6lu",
	"m45wYDHkFFi2ZCtdhXaOjk7GJ0dHsEzRpKisRWsZ/TqHk+uJUD4Tl9w6FPG1O0wsDs1C57JMypuyGOVc",
	"mFHw01j85LlVrROJeiLsyBmyG2CxqxbBd9SfK8YhvBRVtVK3Ph8KK2dcWtBEWFPPGKp1YiEFs9TNJFSu",
	"wa7CO7wZRK6c9zThumAmTqOJ6EZ+BcMAwmsaIer7XccpEwKznh3M7yYZwgWqAf0+Ed3f/+1/fTvWMGdF",
	"H37/t//5YJS6QFyBanB+AWGhGqyk8Ali/jfn52NCL1HpiXh48oPd8gJZZkElpKE2ZpSXTbVtNGVvCGdu",
	"zQNrRCSPoBTTTMY3mMB0BVcXTx8P2sN0zb4/XyhM3d5c6CD59nld8q5nyye1AmqxF/2g0HXk0weFc6aS",
	"zKKrnFXUsyYbwmztbO6TH/azis2esk2O4b8GVqWyDRzGu8m6/vThYjx80OAcVnzW+Aalq+3mFn9FxWcc",
	"NUQ0bgRfQxQmjIDNGRfaQFRqVHpNOSnTaQTdMzWX4oQn/YmIJRV+GEoQ79Vpu0+k6RxMjtj//Osr+Lpq",
	"fkIU3AdKnCF3UFRQqtw180WxIwjf+FfqX/nkg8i3S9H9en6Ky9+rHKfEKVxu0NSqnzOprGLsk1L1EH5U",
	"pcEBxdOBGYM5dQJSOBGKGRwQESPRO5xfBNKvOFv34ckPvTZqpN4rX4gIGz1wDqK98eee2/eU2df8+VE4",
	"IvAJYPesx96bo8mjA9eQcE2S7DOxhOeNzFaXiHo75UtnQAbS30JL+/shxsdzOZ9jAvbxO2ntl7iQN1SY",
	"qqiI2mcKWcqZlnnhaPI6ZMPu28qAZdluTubm0sCyrMlbdDWfDoysMW/Unwiflh0aVq0aTEOHRBnLPWaZ",
	"tXR3kLkszVmWHQTSsyyrslpB0dqTe8iD8ieCC1Sr6jyqBqn+nKiX0e7TcLUWu5yT9e6RX5D51KdpocLH",
	"ta1Al8IZat1z0m749TnM6bzvIx3zJzR1CGcraMZO9kDc4/NtyM98XLmB+uvqrC0R6pgxdL1/x2eCWPHr",
	"H3GtziMvKjlmCXTX0rI3hEtpqvRQN1tXZom3HgifKe3VMkKudUkKfCN31C20TmlDuESr21OHh4kI+WmK",
	"Zkr8LMoTOmlewnCFVnfnArrud5PizLi5MOekeUxEpf373Q2Vneg6QUPN+yJgZcINUPJKG3Ffutde+cK1",
	"z+OHbUC6veHnlp76JQV6o9vbNk39gsvGaX0C3az5ER3tpjJoNUbCncZ0t9GHsx53E0jIZWauCHSttAUd",
	"FqxO67BGV0kaPsPeiY1oIiwLsTi6NqSPKVRKZltgp0dHVRSUuA93XWOojwsYORGRU8op9VjzOSmlVcDV",
	"7rpWHDSEJ1hkcuWyAUzKDCyZMCSxuEGKK9EgZWHZGbpacSVLY1VYxxHsB9WO1B5sX0Y33azm/QJJzB/d",
	"8rGlJVHlgTjYjuzv7IC7Wy30WdKuV4uXv549frRSfK+B1KdkfwaNqAa1JmH7Pqsb9HYrDWs8xL9VWaxm",
	"V0ly9+rns8HJN98SSXsvVR+aFmp/IoLFSSRXsYGwgH7QGJu6ohdhlappZV1D1+w2VSteKXd9V9H2ba/v",
	"EsDteso8pIB78feUrhVJYGRZB/1xvT/C6C5xOwkfXSYS9XEaBGNjIojr2CedqIWjo4fjMRVJukOo+tI6",
	"kDs5/wgYGCkHOpXKVFCw2wvMbmOQyi1RyIzHq6idwdSq1r8Yl2mpjP8ClvDexNDgHPEtVD5vemgw+vzg",
	"0GUt9kOdg9wXOzh3uDRyF+IkI8LbGjVSkvsS2U2FU5/JGn7s6AdYg/ad/LbS2FJ1ZSsf4i4L10HsjAAF",
	"uU+SXVgmlMCkurECfvW3UYwu3V0Uk467V6LNutoRa6nfftGSKHDHssDjelngN/dbFXi3vpWNWz/2Nuvd",
	"0RRqR21eOB732j1V3rHY8AWurwqhyYHRDSTgrqbQASm/2xn4SamL/t9vs7Z9o/0vaBT4GdpyrFEteIzU",
	"oqqwkP3mVk/b55r2DBIsUCQo4hV0n/xoGQzdK0Chm0QuxabfjC+Qmjda5oc1YDv4emCHpu0ojPJIvLPa",
	"utZnnuPequuDK4hrJbD/ceqH78YpGjc27K8ivmO70IM5y1k4xoLq9WYQsOYfUdnrMTesAbq+2LjWuz8U",
	"Hq9x37/UKP9tK3dtAPzLaHDbtzbcc7lrE6laTB66RqpR33o/+TT3W/HxV+8Cl6G7KHS3rrKYymQVwf/9",
	"P9uXXORSJu2/uOsvenesBwn2Yx27V60I3MK9W4p32wpZt5D7y1elfvEa0ybAoMurst9d5L9Lt7gdOuN7",
	"I79XztHrGP6ngP2+COmXcHUsdPP1LamUw0G9VwT1RiVDoPcx6chS4AFk0W4+fNbrod9Sl5o4bcl6tl//",
	"cWXH/SJvMNr//0TiP4IkuhuVXLgajmzlIX+wFMlxVL/UQu90BfxSa+cC3Wh9zQM8eXr1uA88oX+iXh82",
	"e8EMJyL0inAd8yK6WEXx2LWrdF9Sd4eqjyV0I5ZlUW+d2GKf+drfqwFnLsFvXU1fb8XXvCHEXa8wnIjL",
	"cAFW1NjxqX3xVC5Fqz/P6p6/NAB0kI+ipTtTrRkpBcyrXC765Nb/n+2ZPju32rpwpJ3w1wfsDJyvA1YS",
	"9tybBvxpZlEDrxsewOO6JtQk+HY+MLKbvz39xPVgqBEvMDOSmSuEZS7rLHLJsxEsmUGVM3VDd+VA13Wv",
	"gn+eCJZlvhXh+hlfBRF112zGcpheFNDdZ8I7s8/yBpGgwoS8TpQyTuuh4CFTLv+YzYxPXkyULBK5FFC9",
	"pg1bTURgLuu2MUPYxTSWVvLu5BoWNGdZ1sCrS2xr8tDa9GsNCLfd0OyLrhty+T4B7P6WoTb6dKDvfL5a",
	"4rsRXr3Ratsl/zXXsgsn+S25qNkfkeDsqRLwm3RmV90H6Tsxkwimm8rWx3hX2qMqBZIHO4lvjaN9cPWW",
	"1Ak4OQhj4ayxhYngCfWKF/Nwy1pNX4euVOCV+l69WxIF3LjxZcoZshs9Eetk9x1kUaeJdpL4Ikr7PwrN",
	"X9QvCFN/DJz/ByjWoMs4bV6f5nQ0rj2S+QKGBiUMhDQD0sjv6kshUrVGY2NKJ3ra3QNthCkLPVqHPXdE",
	"yAqpjG4kx++6IIlrcP73VZDNP4C7M8kryEj9umNMLAH1va6dW7sSllzoUzjgmpyJOOyeHFhfk1NSYXh1",
	"VU7fXY4wEVsXOcHt9ziJMsua9+xE/qKdaCJUKTab0rjaleb9Ox4OO6KF6wurviBFrydpQWV3h5OjXnc9",
	"ln/0DyivttcarvLqsiTnoo7+siCkp+HVol07cdnYCS6gu+AMXimGM35jR6G+ItSeW5+ORqzgQ5d8OaRU",
	"mFRS2s6WZ5EavRBqUhVgc6DT0ah6+fT78fdjqlX1y30fBIOPZ9nB/TcU3q5/duHF2jdNSq/9YGFQ+5jL",
	"hYtvrL8pNY/rX2gjXQzk7Yf/FwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
