// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accountrepo

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         int64              `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	ActorKind  string             `json:"actor_kind"`
	Action     string             `json:"action"`
	TargetKind *string            `json:"target_kind"`
	TargetID   *string            `json:"target_id"`
	Metadata   []byte             `json:"metadata"`
	Ip         *netip.Addr        `json:"ip"`
	UserAgent  *string            `json:"user_agent"`
}

type Permission struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	TokenHash       []byte             `json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason    *string            `json:"revoke_reason"`
	ReplacedByID    pgtype.UUID        `json:"replaced_by_id"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	IssuedIp        *netip.Addr        `json:"issued_ip"`
	IssuedUserAgent *string            `json:"issued_user_agent"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID        `json:"role_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	GrantedAt    pgtype.Timestamptz `json:"granted_at"`
	GrantedBy    pgtype.UUID        `json:"granted_by"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	OidcSubject       *string            `json:"oidc_subject"`
	Email             string             `json:"email"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         *string            `json:"avatar_url"`
	Role              string             `json:"role"`
	Locale            string             `json:"locale"`
	Timezone          string             `json:"timezone"`
	TokenVersion      int32              `json:"token_version"`
	DisabledAt        pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PasswordHash      *string            `json:"password_hash"`
	PasswordUpdatedAt pgtype.Timestamptz `json:"password_updated_at"`
}

type UserRole struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
	GrantedBy pgtype.UUID        `json:"granted_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}
