// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accountrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ── User ↔ Role assignment ────────────────────────────────────────
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	// ── User lifecycle (auth-related) ─────────────────────────────────
	// Invalidates all outstanding access tokens for this user (forced logout-all).
	// Refresh tokens are NOT touched here; revoke them separately when needed.
	BumpUserTokenVersion(ctx context.Context, id pgtype.UUID) (int32, error)
	// Registration. password_hash is an Argon2id PHC string; oidc_subject stays NULL.
	CreateLocalUser(ctx context.Context, arg CreateLocalUserParams) (User, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	// ── Refresh tokens ────────────────────────────────────────────────
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	DeleteRole(ctx context.Context, id pgtype.UUID) error
	DisableUser(ctx context.Context, id pgtype.UUID) error
	EnableUser(ctx context.Context, id pgtype.UUID) error
	// Returns the union of permissions granted (directly or via ancestor roles)
	// for ALL roles assigned to a user. Skips expired role assignments.
	GetEffectivePermissions(ctx context.Context, userID pgtype.UUID) ([]string, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	// ── Hierarchy resolution ──────────────────────────────────────────
	// Walks parent chain. Returns the role itself plus all ancestors, in depth order.
	GetRoleAncestors(ctx context.Context, id pgtype.UUID) ([]GetRoleAncestorsRow, error)
	GetRoleByCode(ctx context.Context, code string) (Role, error)
	GetRoleByID(ctx context.Context, id pgtype.UUID) (Role, error)
	// Minimal projection used by JWT middleware on each request to validate
	// token_version + disabled state. Indexed PK lookup.
	GetUserAuthSnapshot(ctx context.Context, id pgtype.UUID) (GetUserAuthSnapshotRow, error)
	// Primary login lookup (ADR-06 local auth). Email is UNIQUE.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GrantPermissionToRole(ctx context.Context, arg GrantPermissionToRoleParams) error
	ListActiveRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) ([]ListActiveRefreshTokensForUserRow, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditLog, error)
	// ── Permissions ───────────────────────────────────────────────────
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListRolePermissions(ctx context.Context, roleID pgtype.UUID) ([]Permission, error)
	// ── Roles ─────────────────────────────────────────────────────────
	ListRoles(ctx context.Context) ([]Role, error)
	ListUserRoles(ctx context.Context, userID pgtype.UUID) ([]Role, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error)
	MarkRefreshTokenReplaced(ctx context.Context, arg MarkRefreshTokenReplacedParams) error
	// Run from a periodic job. Anything past expiry + grace can be hard-deleted.
	PurgeExpiredRefreshTokens(ctx context.Context) error
	RevokeAllRefreshTokensForUser(ctx context.Context, arg RevokeAllRefreshTokensForUserParams) error
	RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	// Walks the rotation chain forward and backward from the given token,
	// revoking every link. Used on suspected token theft (reuse detection).
	RevokeRefreshTokenChain(ctx context.Context, arg RevokeRefreshTokenChainParams) error
	RevokeRoleFromUser(ctx context.Context, arg RevokeRoleFromUserParams) error
	// Change-password / admin reset. Pair with BumpUserTokenVersion to force a
	// re-login everywhere after a credential change.
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	// ── Audit log ─────────────────────────────────────────────────────
	WriteAuditEvent(ctx context.Context, arg WriteAuditEventParams) error
}

var _ Querier = (*Queries)(nil)
