// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package movierepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// movie module queries (first domain vertical). sqlc input only — regenerate with
	// `make sqlc`. Owner-scoped mutations; published-or-owner reads. Asset ids are
	// validated via mediaapi (no cross-module FK) and reaped via the
	// media:asset_deleted consumer. tenant_id is filled by its column DEFAULT
	// (RequireTenant sets app.current_tenant per request) — never inserted here.
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	DeleteMovie(ctx context.Context, id pgtype.UUID) error
	GetMovie(ctx context.Context, id pgtype.UUID) (Movie, error)
	GetMovieOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	ListOwnMovies(ctx context.Context, arg ListOwnMoviesParams) ([]Movie, error)
	ListPublishedMovies(ctx context.Context, arg ListPublishedMoviesParams) ([]Movie, error)
	NullPosterByAsset(ctx context.Context, posterAssetID pgtype.UUID) error
	// ══ media:asset_deleted consumer ══════════════════════════════════════════
	// NullVideoByAsset also unpublishes: a published movie with no video is broken.
	NullVideoByAsset(ctx context.Context, videoAssetID pgtype.UUID) error
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
	UpdateMovieStatus(ctx context.Context, arg UpdateMovieStatusParams) (Movie, error)
}

var _ Querier = (*Queries)(nil)
