// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenantrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMembership(ctx context.Context, arg CreateMembershipParams) error
	// CreatePersonalOrg is idempotent: the unique partial index
	// organizations_personal_owner_idx (0018) makes a concurrent second call a
	// no-op (ON CONFLICT DO NOTHING → zero rows → caller re-fetches).
	CreatePersonalOrg(ctx context.Context, arg CreatePersonalOrgParams) (Organization, error)
	// Tenant control-plane queries (ADR-07 Phase 1). These tables are NOT
	// tenant-scoped (no RLS), so they run on the pool directly during tenant
	// resolution — before any BeginTenantScope tx exists.
	GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetPersonalOrgForUser(ctx context.Context, ownerID pgtype.UUID) (Organization, error)
	IsMember(ctx context.Context, arg IsMemberParams) (bool, error)
	// ListAllOrganizationIDs returns every tenant, for the worker's cross-tenant
	// periodic sweeps. `organizations` is deliberately NOT an RLS-protected table
	// (ADR-07: the tenant registry itself must be readable to resolve a scope), so
	// this stays correct after the portal_app cutover — which is what lets a sweep
	// iterate tenants instead of needing BYPASSRLS.
	ListAllOrganizationIDs(ctx context.Context) ([]pgtype.UUID, error)
	ListOrganizationsForUser(ctx context.Context, userID pgtype.UUID) ([]Organization, error)
}

var _ Querier = (*Queries)(nil)
