// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notifyrepo

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID               pgtype.UUID        `json:"id"`
	OwnerID          pgtype.UUID        `json:"owner_id"`
	Kind             string             `json:"kind"`
	Status           string             `json:"status"`
	SourceKey        string             `json:"source_key"`
	OutputPrefix     *string            `json:"output_prefix"`
	MimeType         string             `json:"mime_type"`
	SizeBytes        int64              `json:"size_bytes"`
	DurationMs       *int32             `json:"duration_ms"`
	Width            *int32             `json:"width"`
	Height           *int32             `json:"height"`
	ErrorMessage     *string            `json:"error_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Title            *string            `json:"title"`
	OriginalFilename *string            `json:"original_filename"`
	Origin           string             `json:"origin"`
}

type AuditLog struct {
	ID         int64              `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	ActorKind  string             `json:"actor_kind"`
	Action     string             `json:"action"`
	TargetKind *string            `json:"target_kind"`
	TargetID   *string            `json:"target_id"`
	Metadata   []byte             `json:"metadata"`
	Ip         *netip.Addr        `json:"ip"`
	UserAgent  *string            `json:"user_agent"`
}

type JournalEntry struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	BodyMd     string             `json:"body_md"`
	Mood       *string            `json:"mood"`
	AssetIds   []pgtype.UUID      `json:"asset_ids"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type MediaAssetVariant struct {
	ID         pgtype.UUID        `json:"id"`
	AssetID    pgtype.UUID        `json:"asset_id"`
	Variant    string             `json:"variant"`
	StorageKey string             `json:"storage_key"`
	Width      int32              `json:"width"`
	Height     int32              `json:"height"`
	SizeBytes  int64              `json:"size_bytes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      *string            `json:"body"`
	Data      []byte             `json:"data"`
	DedupKey  *string            `json:"dedup_key"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationPreference struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
	InApp  bool        `json:"in_app"`
	Email  bool        `json:"email"`
	Push   bool        `json:"push"`
	Muted  bool        `json:"muted"`
}

type OpsBackupRun struct {
	ID         pgtype.UUID        `json:"id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Status     string             `json:"status"`
	SizeBytes  *int64             `json:"size_bytes"`
	StorageKey *string            `json:"storage_key"`
	Error      *string            `json:"error"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	TokenHash       []byte             `json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason    *string            `json:"revoke_reason"`
	ReplacedByID    pgtype.UUID        `json:"replaced_by_id"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	IssuedIp        *netip.Addr        `json:"issued_ip"`
	IssuedUserAgent *string            `json:"issued_user_agent"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID        `json:"role_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	GrantedAt    pgtype.Timestamptz `json:"granted_at"`
	GrantedBy    pgtype.UUID        `json:"granted_by"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	OidcSubject       *string            `json:"oidc_subject"`
	Email             string             `json:"email"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         *string            `json:"avatar_url"`
	Role              string             `json:"role"`
	Locale            string             `json:"locale"`
	Timezone          string             `json:"timezone"`
	TokenVersion      int32              `json:"token_version"`
	DisabledAt        pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PasswordHash      *string            `json:"password_hash"`
	PasswordUpdatedAt pgtype.Timestamptz `json:"password_updated_at"`
}

type UserRole struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
	GrantedBy pgtype.UUID        `json:"granted_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type WebPushSubscription struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Endpoint   string             `json:"endpoint"`
	P256dh     string             `json:"p256dh"`
	Auth       string             `json:"auth"`
	UserAgent  *string            `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}
