// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notifyrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Unread badge; backed by the partial notifications_unread_idx.
	CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error)
	// Per-type preference; an absent row means the module default (§6).
	GetNotificationPreference(ctx context.Context, arg GetNotificationPreferenceParams) (GetNotificationPreferenceRow, error)
	// notify module queries (SPEC-04). sqlc input only — regenerate with `make sqlc`;
	// never hand-edit the *.sql.go output.
	// Insert an in-app notification. When @dedup_key is present the partial unique
	// index (user_id, type, dedup_key) WHERE dedup_key IS NOT NULL makes a redelivered
	// dispatch a no-op: DO NOTHING returns zero rows, which the adapter reads as
	// "conflict" (inserted=false) so channel fan-out is skipped too. A NULL dedup_key
	// never conflicts (the index excludes it) and always inserts.
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error)
	ListNotificationPreferences(ctx context.Context, userID pgtype.UUID) ([]ListNotificationPreferencesRow, error)
	// Keyset page, newest first. @unread_only restricts to unread rows (the bell's
	// ?status=unread). A NULL @cursor_created_at starts at the top; the (created_at,
	// id) keyset is backed by notifications_user_cursor_idx.
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	// Read-all with an optional 'before' watermark: only rows at/older than the
	// newest rendered item (@before_created_at, @before_id) are marked, so rows that
	// arrived after the dropdown rendered stay unread. A NULL watermark marks all.
	MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error
	// Idempotent, owner-scoped. COALESCE keeps the first read_at stamp so a second
	// call is a no-op. RETURNING id yields no row when the id is missing or belongs
	// to another user → the handler answers 404 (never leaks existence).
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (pgtype.UUID, error)
	// P2 retention janitor: read > 90d and unread > 180d, exempting the non-mutable
	// security type. Batched deletes are a future refinement (§P2).
	PurgeOldNotifications(ctx context.Context) error
	// P1.3 preferences write.
	UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) error
}

var _ Querier = (*Queries)(nil)
