// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package layoutrepo

import (
	"context"
)

type Querier interface {
	// The other half of a whole-set save: anything the client did not send is gone.
	// System rows are exempt — they are the shell's own navigation, and a client
	// that omits them (a stale tab, a bad payload) must not be able to empty the
	// menu into a state nobody can fix from inside the UI.
	DeleteMenuItemsExcept(ctx context.Context, keys []string) error
	// The shell's navigation and dashboard layout. Read by every authenticated
	// request that renders the app frame; written only from the admin console.
	// Everything, hidden rows included. The caller decides what to show: the admin
	// console wants the full list, the shell filters it. Doing the visible/permission
	// filtering here would mean two near-identical queries drifting apart.
	ListMenuItems(ctx context.Context) ([]ListMenuItemsRow, error)
	ListWidgets(ctx context.Context) ([]ListWidgetsRow, error)
	// Widgets are never created or deleted here: `key` has to match a React
	// component, so the catalogue is fixed by the frontend registry and only
	// placement is editable.
	UpdateWidget(ctx context.Context, arg UpdateWidgetParams) error
	// One row of a whole-set save. `key` is the conflict target rather than `id`
	// because a newly added row has no id yet on the client, and a stable key is
	// what makes "add" and "edit" the same statement.
	UpsertMenuItem(ctx context.Context, arg UpsertMenuItemParams) error
}

var _ Querier = (*Queries)(nil)
