// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package socialrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Only a pending row moves; re-accepting an accepted one returns no rows, which
	// keeps a double-click from rewriting responded_at.
	AcceptRequest(ctx context.Context, arg AcceptRequestParams) (SocialConnection, error)
	// The header badge.
	CountIncoming(ctx context.Context, addresseeID pgtype.UUID) (int64, error)
	// social module queries — connections between accounts (0037). sqlc input only.
	//
	// These return IDS, never names. `users` belongs to the account module and this
	// module may not join it (MODULES.md); the service resolves display names
	// through account's api/ package in one batch afterwards.
	//
	// Every statement is additionally fenced by the row-level policies from 0037,
	// which key on `app.current_user`. The predicates below are therefore about
	// INTENT ("the requests waiting on me"), not about isolation: a missing
	// predicate would return fewer rows, never someone else's.
	// Send a request. The pair unique index (either direction) is what makes a
	// duplicate impossible; the caller turns that conflict into "already connected
	// or already asked" rather than a 500.
	CreateRequest(ctx context.Context, arg CreateRequestParams) (SocialConnection, error)
	// Withdraw, decline, or disconnect — the same statement for all three, because
	// the row means the same thing in every case: this link no longer exists.
	DeleteConnection(ctx context.Context, arg DeleteConnectionParams) (SocialConnection, error)
	// The relationship between two accounts, whichever way it was created.
	FindBetween(ctx context.Context, arg FindBetweenParams) (SocialConnection, error)
	GetConnection(ctx context.Context, id pgtype.UUID) (SocialConnection, error)
	ListAccepted(ctx context.Context, me pgtype.UUID) ([]SocialConnection, error)
	// Every account the caller already has any relationship with, pending or not —
	// what the suggestion list subtracts so it stops offering people you have
	// already asked.
	// The cast is what makes sqlc type this column as uuid rather than interface{}:
	// a bare CASE has no declared type for it to read.
	ListCounterpartIDs(ctx context.Context, me pgtype.UUID) ([]pgtype.UUID, error)
	// Requests waiting on the caller's answer.
	ListIncoming(ctx context.Context, me pgtype.UUID) ([]SocialConnection, error)
	// Requests the caller has sent and nobody has answered yet.
	ListOutgoing(ctx context.Context, me pgtype.UUID) ([]SocialConnection, error)
}

var _ Querier = (*Queries)(nil)
