/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Local password login
         * @description Verifies `email` + `password` against `users.password_hash` (Argon2id,
         *     constant-time). On success, mints an access JWT + refresh token, sets the
         *     `portal_access` / `portal_refresh` / `portal_session` cookies, and returns
         *     the access token in the body for API clients. Brute-force attempts are
         *     rate-limited per IP and per account (429).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a local account
         * @description Creates a local account (Argon2id hash) and seeds the default `user`
         *     role. Returns **201 without a session** — the user is sent back to
         *     `/login` to sign in with the new credentials. Deployments that want
         *     invite-only signup gate this route at the router.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate refresh token, mint new access token
         * @description Reads the refresh token from the `portal_refresh` cookie (browser) or the
         *     `refresh_token` body field (API client). Rotates the token (old is
         *     revoked, new is issued) and returns a fresh access token. Reuse of an
         *     already-rotated token revokes the entire chain (token theft) and emits an
         *     `account.refresh.reuse_detected` audit event.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke current session and bump token_version */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke every session for the current user
         * @description Revokes all refresh tokens and bumps `users.token_version`,
         *     invalidating any access tokens already in flight.
         */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password-reset email (SPEC-04 P0.3)
         * @description Enumeration-safe: always returns **202** whether or not the email is
         *     registered, and responds before the lookup/mint/enqueue so timing does
         *     not leak account existence. On success (registered, enabled, not
         *     throttled) a single-use reset token is minted and a `notify:dispatch`
         *     (`account.password_reset`, email channel) is enqueued. Per-email
         *     (≥60s gap, ≤3/h) and per-IP throttles apply; the per-IP limit answers
         *     429 (revealing nothing about any email). Account-owned; unblocked by SPEC-04.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consume a reset token and set a new password (SPEC-04 P0.3)
         * @description Verifies the one-time reset token (SHA-256 hash lookup, constant-time),
         *     sets the new Argon2id password, bumps `token_version` and revokes all
         *     refresh tokens (every session is revoked, ADR-06), then consumes the
         *     token. Expired / used / unknown tokens — and tokens for a since-disabled
         *     user — return **400** `account/invalid-reset-token`; a too-short password
         *     returns **400** `account/password-policy`.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's notifications (SPEC-04 P0.1)
         * @description Newest first (`created_at DESC, id DESC`), cursor-paginated.
         *     `status=unread` restricts to unread rows; default (`all`) returns
         *     read+unread. Always includes `unread_count` for the bell badge.
         *     Requires `notifications:read:own`.
         */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark one notification read (idempotent)
         * @description Idempotent, owner-scoped. Requires `notifications:write:own`. A notification
         *     id belonging to another user (or missing) returns 404 — it never leaks
         *     existence.
         */
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark all notifications read, optionally up to a watermark
         * @description Marks unread rows at/older than the `before` watermark read (absent =
         *     all). The watermark is the `(created_at, id)` cursor of the newest
         *     rendered item, so rows that arrived after the dropdown rendered stay
         *     unread. Idempotent. Requires `notifications:write:own`.
         */
        post: operations["markAllNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's assets */
        get: operations["listAssets"];
        put?: never;
        /**
         * Begin a media upload
         * @description Creates the asset row and returns a **presigned PUT** for the original
         *     bytes. The browser PUTs directly to object storage (prod/R2); in dev it
         *     may proxy through `PUT /assets/{id}/source`. Then call
         *     `POST /assets/{id}/complete` to enqueue transcoding.
         */
        post: operations["createAssetUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get asset metadata */
        get: operations["getAsset"];
        put?: never;
        post?: never;
        /**
         * Delete an asset (owner, or `assets:delete:any`)
         * @description Soft-deletes (`status='deleting'`, hidden from listings) then purges the
         *     asset's storage objects (original, HLS, variants) and rows. Enforced via
         *     `RequireOwnerOrPermission`. Idempotent — an already-gone asset returns 404.
         */
        delete: operations["deleteAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * API-proxied upload of the original bytes (dev path)
         * @description Streams the raw original into object storage via the API. Used in dev
         *     where the presigned PUT endpoint is not browser-reachable; prod uploads
         *     go straight to the presigned URL from `POST /assets`. Body is the raw
         *     file; `Content-Type` is the media type.
         */
        put: operations["uploadAssetSource"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm the upload and enqueue processing
         * @description Marks the source uploaded and enqueues a transcode (video) or thumbnail
         *     (image) job on Asynq. Asset status transitions to `processing` and
         *     eventually `ready` or `failed`.
         */
        post: operations["completeAssetUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/original": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the original file (owner-only)
         * @description Streams the source object as an attachment with the sniffed content type.
         *     Owner-authenticated only — the original retains full EXIF/GPS (unlike the
         *     metadata-stripped variants), so it is never served through the public-ish
         *     variant/HLS scheme.
         */
        get: operations["downloadAssetOriginal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/variants/{variant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a derived variant (public-ish)
         * @description Serves a metadata-stripped WebP variant (`thumb`/`medium`/`poster`). Same
         *     public stance as the HLS proxy — variants carry no EXIF, so they are safe
         *     to be semi-public; the private original is behind `/assets/{id}/original`.
         */
        get: operations["getAssetVariant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/hls/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public HLS proxy (manifest + segments)
         * @description Serves the HLS master/variant manifests and media segments for a `ready`
         *     asset. **Public** (no bearer) so the `<video>`/Vidstack player can fetch
         *     segments directly; access to the asset id is the capability.
         */
        get: operations["getAssetHLS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch playback progress */
        get: operations["getAssetProgress"];
        /** Save playback progress */
        put: operations["putAssetProgress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active progress items across modules (SPEC-07)
         * @description Returns the unified "Continue Watching/Reading" rail for the current user.
         */
        get: operations["getContinueItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journal/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's journal entries (newest occurred_at first) */
        get: operations["listJournalEntries"];
        put?: never;
        /** Create a journal entry */
        post: operations["createJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journal/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Fetch one journal entry */
        get: operations["getJournalEntry"];
        put?: never;
        post?: never;
        /** Delete a journal entry (idempotent) */
        delete: operations["deleteJournalEntry"];
        options?: never;
        head?: never;
        /** Partially update a journal entry */
        patch: operations["patchJournalEntry"];
        trace?: never;
    };
    "/ops/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backup freshness sentinel (admin)
         * @description Reports whether the nightly Postgres backup is healthy (SPEC-09 P0.5).
         *     `state` precedence, first match wins: `failed` (most recent completed run
         *     failed) → `stale` (no success within 26 h, including never-ran, where
         *     `last_success_at` and `hours_since_success` are null) → `ok`. A `running`
         *     run is not completed and never changes `state`.
         */
        get: operations["getOpsStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bank/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's accounts with derived balances */
        get: operations["listBankAccounts"];
        put?: never;
        /** Create an account */
        post: operations["createBankAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bank/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an empty account
         * @description Accounts with transactions cannot be deleted, only archived (`bank/account-not-empty`).
         */
        delete: operations["deleteBankAccount"];
        options?: never;
        head?: never;
        /**
         * Update an account (name / archived / currency)
         * @description currency is immutable once the account has transactions (`bank/account-not-mutable`).
         */
        patch: operations["updateBankAccount"];
        trace?: never;
    };
    "/bank/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's own + seed categories */
        get: operations["listBankCategories"];
        put?: never;
        /** Create a category */
        post: operations["createBankCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bank/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a category (optionally reassigning its transactions)
         * @description Without `reassign_to`, a category with transactions returns 409 `bank/category-in-use`. Seeds are undeletable (404). Children promote to top level; budgets cascade.
         */
        delete: operations["deleteBankCategory"];
        options?: never;
        head?: never;
        /**
         * Update a category (name / parent)
         * @description kind is immutable; re-parenting re-runs the top-level + same-kind checks (`bank/invalid-category-parent`). Seeds are not mutable (404).
         */
        patch: operations["updateBankCategory"];
        trace?: never;
    };
    "/bank/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions (cursor paged, newest first) */
        get: operations["listBankTransactions"];
        put?: never;
        /** Create a manual transaction */
        post: operations["createBankTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bank/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a transaction
         * @description A transfer leg cannot be deleted here (409 `bank/is-transfer-leg`).
         */
        delete: operations["deleteBankTransaction"];
        options?: never;
        head?: never;
        /**
         * Update a transaction
         * @description A transfer leg cannot be edited here (409 `bank/is-transfer-leg`) — use /bank/transfers/{transfer_id}.
         */
        patch: operations["updateBankTransaction"];
        trace?: never;
    };
    "/bank/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an inter-account transfer (paired debit + credit) */
        post: operations["createBankTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bank/transfers/{transfer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transfer_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a transfer (both legs) atomically */
        delete: operations["deleteBankTransfer"];
        options?: never;
        head?: never;
        /** Update both legs of a transfer atomically */
        patch: operations["updateBankTransfer"];
        trace?: never;
    };
    "/bank/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List monthly budgets with spent (tree, incl. children) */
        get: operations["listBankBudgets"];
        /** Upsert a monthly budget (amount 0 or null deletes it) */
        put: operations["setBankBudget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bank/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ledger dashboard (balances, month flow, budgets, recent) */
        get: operations["getBankDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JournalEntry: {
            /** Format: uuid */
            id: string;
            body_md: string;
            mood?: string | null;
            asset_ids: string[];
            /** Format: date-time */
            occurred_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Create requires body_md; PATCH accepts any subset of the fields. `asset_ids`
         *     is rejected with 422 `journal/invalid-asset` until photo attachments (P1.5).
         */
        JournalEntryWrite: {
            body_md?: string;
            mood?: string | null;
            /**
             * Format: date-time
             * @description Optional; defaults to now. Backdating and future-dating are allowed.
             */
            occurred_at?: string;
        };
        /** @description One row of the backup-run ledger (`ops_backup_runs`). */
        OpsBackupRun: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "running" | "ok" | "failed";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: int64 */
            size_bytes?: number | null;
            storage_key?: string | null;
            error?: string | null;
        };
        /**
         * @description Freshness sentinel for the nightly Postgres backup (P0.5). `last_success_at`
         *     and `hours_since_success` are both null when a backup has never succeeded.
         */
        OpsStatus: {
            /**
             * @description `failed` (most recent completed run failed) → `stale` (no success within
             *     26 h, incl. never-ran) → `ok`. A running run never changes state.
             * @enum {string}
             */
            state: "ok" | "stale" | "failed";
            /**
             * Format: date-time
             * @description Completion time of the most recent successful run; null if none.
             */
            last_success_at?: string | null;
            /** @description Hours since the last success; null if none. */
            hours_since_success?: number | null;
            /** @description The most recently started run of any status; null if none. */
            last_run?: components["schemas"]["OpsBackupRun"] | null;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            db?: boolean;
            cache?: boolean;
        };
        BankAccount: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            type: "cash" | "checking" | "savings" | "credit_card" | "ewallet" | "other";
            /**
             * @description ISO-4217
             * @example VND
             */
            currency: string;
            /** Format: int64 */
            opening_balance: number;
            /**
             * Format: int64
             * @description Derived (opening + Σcredits − Σdebits); always current.
             */
            balance: number;
            archived: boolean;
            /** Format: date-time */
            created_at: string;
        };
        BankAccountCreate: {
            name: string;
            /** @enum {string} */
            type: "cash" | "checking" | "savings" | "credit_card" | "ewallet" | "other";
            /** @default VND */
            currency: string;
            /**
             * Format: int64
             * @default 0
             */
            opening_balance: number;
        };
        BankAccountPatch: {
            name?: string;
            archived?: boolean;
            /** @description Only mutable while the account is empty. */
            currency?: string;
        };
        BankCategory: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parent_id?: string | null;
            name: string;
            /** @enum {string} */
            kind: "income" | "expense";
            /** @description A user_id-NULL default (visible to all */
            seed: boolean;
        };
        BankCategoryCreate: {
            name: string;
            /** @enum {string} */
            kind: "income" | "expense";
            /**
             * Format: uuid
             * @description Must be a top-level category of the same kind.
             */
            parent_id?: string | null;
        };
        /** @description kind is immutable. `parent_id` present (incl. null) re-parents; absent leaves it. */
        BankCategoryPatch: {
            name?: string;
            /** Format: uuid */
            parent_id?: string | null;
        };
        BankTransaction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            account_id: string;
            /** Format: uuid */
            category_id?: string | null;
            /**
             * Format: int64
             * @description Strictly positive minor units.
             */
            amount: number;
            /** @enum {string} */
            direction: "debit" | "credit";
            /** Format: uuid */
            transfer_id?: string | null;
            /** @description True for a transfer leg (transfer_id set AND category_id null). */
            is_transfer: boolean;
            /**
             * Format: date
             * @description YYYY-MM-DD
             */
            occurred_at: string;
            note?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        BankTransactionCreate: {
            /** Format: uuid */
            account_id: string;
            /**
             * Format: uuid
             * @description Own or seed; kind must match direction.
             */
            category_id: string;
            /** Format: int64 */
            amount: number;
            /** @enum {string} */
            direction: "debit" | "credit";
            /**
             * Format: date
             * @description Defaults to today.
             */
            occurred_at?: string;
            note?: string | null;
        };
        BankTransactionPatch: {
            /** Format: uuid */
            account_id?: string;
            /** Format: uuid */
            category_id?: string;
            /** Format: int64 */
            amount?: number;
            /** @enum {string} */
            direction?: "debit" | "credit";
            /** Format: date */
            occurred_at?: string;
            note?: string | null;
        };
        BankTransferCreate: {
            /** Format: uuid */
            from_account: string;
            /** Format: uuid */
            to_account: string;
            /** Format: int64 */
            amount: number;
            /** Format: date */
            occurred_at?: string;
            note?: string | null;
        };
        BankTransferPatch: {
            /** Format: uuid */
            from_account?: string;
            /** Format: uuid */
            to_account?: string;
            /** Format: int64 */
            amount?: number;
            /** Format: date */
            occurred_at?: string;
            note?: string | null;
        };
        BankTransfer: {
            /** Format: uuid */
            transfer_id?: string | null;
            legs: components["schemas"]["BankTransaction"][];
        };
        BankBudgetLine: {
            /** Format: uuid */
            category_id: string;
            /** Format: uuid */
            parent_id?: string | null;
            name: string;
            parent_name?: string | null;
            /** Format: int64 */
            amount: number;
            /**
             * Format: int64
             * @description Σ expense debits this month incl. children
             */
            spent: number;
        };
        BankBudgetWrite: {
            /**
             * Format: uuid
             * @description Must be expense-kind.
             */
            category_id: string;
            /** @description YYYY-MM */
            month: string;
            /**
             * Format: int64
             * @description 0 or null deletes the budget.
             */
            amount?: number | null;
        };
        BankDashboard: {
            month: string;
            accounts: components["schemas"]["BankAccount"][];
            /** Format: int64 */
            income: number;
            /** Format: int64 */
            expense: number;
            budgets: components["schemas"]["BankBudgetLine"][];
            recent: components["schemas"]["BankTransaction"][];
        };
        /**
         * @description RFC 7807 problem detail, served as `application/problem+json`. `type` is a
         *     stable URI (also the i18n key); Portal adds the extensions below.
         */
        Problem: {
            /**
             * Format: uri
             * @description Stable problem-type URI (i18n key).
             * @default about:blank
             */
            type: string;
            /** @description Short, human-readable summary of the problem type. */
            title: string;
            /** @description HTTP status code, repeated for convenience. */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying the specific occurrence.
             */
            instance?: string;
            /** @description Portal-stable machine slug (e.g. `invalid_credentials`). */
            code?: string;
            /** @description For step-up (403) — the ACR the caller must satisfy [D-27]. */
            required_acr?: string;
            /**
             * Format: uri
             * @description For MFA-enrollment (403) — where to enroll a second factor [D-28].
             */
            enrollment_url?: string;
        } & {
            [key: string]: unknown;
        };
        /** @deprecated */
        Error: {
            code: string;
            message: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            /**
             * @description Persist the session (durable refresh cookie) vs a session cookie.
             * @default false
             */
            remember: boolean;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            /** @description Optional; defaults to the email local-part. */
            display_name?: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            /** @description The one-time reset token from the email link. */
            token: string;
            /** Format: password */
            new_password: string;
        };
        AccessToken: {
            access_token: string;
            /** @description seconds until expiry */
            expires_in: number;
            /** @enum {string} */
            token_type: "Bearer";
        };
        LoginResponse: components["schemas"]["AccessToken"] & {
            user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string;
                display_name: string;
                roles: string[];
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            /** Format: uri */
            avatarUrl?: string | null;
        };
        CurrentUser: components["schemas"]["User"] & {
            /** @description Role codes (e.g. ["user","creator"]). Frontend uses these to render UI affordances; the server is the authority on perm checks. */
            roles: string[];
        };
        /** @enum {string} */
        AssetKind: "video" | "audio" | "image";
        /** @enum {string} */
        AssetStatus: "uploaded" | "processing" | "ready" | "failed";
        Asset: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["AssetStatus"];
            kind: components["schemas"]["AssetKind"];
            mimeType: string;
            /** Format: int64 */
            sizeBytes: number;
            durationMs?: number | null;
            width?: number | null;
            height?: number | null;
            /**
             * Format: uri
             * @description Master playlist URL; present once `status` is `ready`.
             */
            hlsUrl?: string | null;
            /** @description Failure reason; present when `status` is `failed`. */
            error?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreateAssetRequest: {
            filename: string;
            /** @default application/octet-stream */
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
        };
        AssetUploadSession: {
            asset: components["schemas"]["Asset"];
            /** @description Presigned request the client performs to store the original. */
            upload: {
                /** Format: uri */
                url: string;
                /** @enum {string} */
                method: "PUT";
                headers?: {
                    [key: string]: string;
                };
            };
        };
        Notification: {
            /** Format: uuid */
            id: string;
            /** @description Open type registry (e.g. `media.asset_ready`). See notify/README.md. */
            type: string;
            title: string;
            body?: string;
            /** @description Target ids / links — e.g. `href` for the bell's click-through. */
            data: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description When the notification was marked read; null while unread.
             */
            read_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        NotificationList: {
            items: components["schemas"]["Notification"][];
            /** @description Unread badge count for the bell. */
            unread_count: number;
            /** @description Keyset cursor for the next page; absent/null on the last page. */
            next_cursor?: string | null;
        };
        UnreadCount: {
            unread_count: number;
        };
        /** @description Exact monetary amount [D-14/D-15]. `amount` is a decimal string to avoid float error. */
        Money: {
            /** @description Decimal string, e.g. "1234.56" (numeric(20,8) at rest). */
            amount: string;
            /** @description ISO 4217 code, e.g. "USD". */
            currency: string;
        };
        /**
         * @description Cursor-paginated envelope. Concrete endpoints override `items` with their
         *     element type (OpenAPI has no generics — compose with `allOf` + an `items`
         *     override, or document the element type in the operation).
         */
        PaginatedResult: {
            items: unknown[];
            /** @description Opaque cursor for the next page; null on the last page. */
            nextCursor?: string | null;
            /** @description Total count when cheap to compute; otherwise omitted. */
            total?: number | null;
        };
        /**
         * @description Resolved tenant scope for the `/t/{tenant}/…` prefix [D-23]. Multi-tenancy
         *     is deferred to Phase 1; v1 runs single-tenant (`me`).
         */
        TenantContext: {
            /** Format: uuid */
            tenantId: string;
            slug: string;
            /** @enum {string} */
            kind?: "org" | "household";
        };
        PlaybackProgress: {
            /** Format: int64 */
            position_ms: number;
            /** @description Fractional completion 0..100. Absent if duration is unknown. */
            progress_pct?: number;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description One "continue watching / reading / listening" entry for the cross-domain
         *     `/continue` rail [D-20]. Aggregated from each vertical's progress table.
         */
        ContinueItem: {
            /** @enum {string} */
            module: "media" | "movie" | "music" | "story" | "comic";
            /** Format: uuid */
            ref_id: string;
            title: string;
            /** @description Fractional completion 0..100. */
            progress_pct: number;
            href: string;
            poster_url?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated, but lacks permission (or step-up required) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit / lockout tripped */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Validation failed */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Conflicts with the resource's current state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        AssetID: string;
        /**
         * @description Tenant slug for the `/t/{tenant}/…` prefix. `me` selects the caller's
         *     personal scope. Multi-tenant routing is deferred to Phase 1 (see
         *     `#/components/schemas/TenantContext`); v1 runs single-tenant.
         */
        TenantSlug: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description A dependency (DB or cache) is down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; cookies set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Account is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created (no session issued) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "registered";
                        /** Format: email */
                        email: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    refresh_token?: string;
                };
            };
        };
        responses: {
            /** @description New access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user (with role codes for UI gating) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Accepted (always, regardless of whether the email exists) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "accepted";
                    };
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password updated (all sessions revoked) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "password_updated";
                    };
                };
            };
            /** @description Invalid/expired/used reset token, or weak password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                status?: "all" | "unread";
                /** @description Opaque keyset cursor from a prior page's `next_cursor`. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notifications page + unread badge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked read; returns the fresh unread count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCount"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No such notification for this user (`notify/notification-not-found`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: {
                /** @description Keyset watermark cursor; absent marks all unread read. */
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the fresh unread count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCount"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAssets: {
        parameters: {
            query?: {
                /** @description Filter by asset kind. */
                kind?: "video" | "image" | "audio";
                /** @description Filter by status; `processing` includes still-`uploading` sessions. */
                status?: "ready" | "processing" | "failed";
                /** @description Opaque keyset cursor from a prior page's `next_cursor`. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's assets (cursor-paginated, newest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        assets: components["schemas"]["Asset"][];
                        /** @description Keyset cursor for the next page; absent/null on the last page. */
                        next_cursor?: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAssetUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetRequest"];
            };
        };
        responses: {
            /** @description Upload session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetUploadSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset (includes `hlsUrl` once status is `ready`) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadAssetSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    completeAssetUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processing started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "processing";
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Source upload is not complete */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description File exceeds the 50 MB limit — object deleted, asset `failed` */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unsupported format (e.g. HEIC) — object deleted, asset `failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    downloadAssetOriginal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The original bytes (attachment) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Asset still uploading — source may be partial */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getAssetVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssetID"];
                variant: "thumb" | "medium" | "poster";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The variant image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": unknown;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAssetHLS: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssetID"];
                /** @description Manifest or segment path under the asset's HLS output prefix. */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HLS manifest or media segment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.apple.mpegurl": unknown;
                    "video/mp2t": unknown;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAssetProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybackProgress"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    putAssetProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssetID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    position_ms: number;
                };
            };
        };
        responses: {
            /** @description Progress saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getContinueItems: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The continue items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ContinueItem"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listJournalEntries: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor from a prior page's next_cursor. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A cursor page of entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["JournalEntry"][];
                        next_cursor?: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createJournalEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalEntryWrite"];
            };
        };
        responses: {
            /** @description Entry created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Validation failed (`journal/invalid-body` · `journal/invalid-mood` · `journal/invalid-asset`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getJournalEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Not found (missing or owned by another user) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteJournalEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    patchJournalEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalEntryWrite"];
            };
        };
        responses: {
            /** @description The updated entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getOpsStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup freshness status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listBankAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accounts: components["schemas"]["BankAccount"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createBankAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankAccountCreate"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankAccount"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    deleteBankAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateBankAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankAccountPatch"];
            };
        };
        responses: {
            /** @description The updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankAccount"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listBankCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Own + seed categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        categories: components["schemas"]["BankCategory"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createBankCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankCategoryCreate"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankCategory"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    deleteBankCategory: {
        parameters: {
            query?: {
                /** @description Move this category's transactions to the target (own or seed, same kind) before deleting. */
                reassign_to?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    updateBankCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankCategoryPatch"];
            };
        };
        responses: {
            /** @description The updated category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankCategory"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listBankTransactions: {
        parameters: {
            query?: {
                account?: string;
                category?: string;
                /** @description YYYY-MM */
                month?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A cursor page of transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        transactions: components["schemas"]["BankTransaction"][];
                        next_cursor?: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createBankTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankTransactionCreate"];
            };
        };
        responses: {
            /** @description Transaction created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransaction"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    deleteBankTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateBankTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankTransactionPatch"];
            };
        };
        responses: {
            /** @description The updated transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransaction"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    createBankTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankTransferCreate"];
            };
        };
        responses: {
            /** @description Transfer created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransfer"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    deleteBankTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transfer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateBankTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transfer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankTransferPatch"];
            };
        };
        responses: {
            /** @description The updated transfer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransfer"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listBankBudgets: {
        parameters: {
            query?: {
                /** @description YYYY-MM (default current month) */
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget lines for the month */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        month: string;
                        budgets: components["schemas"]["BankBudgetLine"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    setBankBudget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankBudgetWrite"];
            };
        };
        responses: {
            /** @description Upserted or deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getBankDashboard: {
        parameters: {
            query?: {
                /** @description YYYY-MM (default current month) */
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The dashboard aggregate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankDashboard"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
