// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mediarepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// id is generated by the app (so the source_key can embed it before insert).
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	GetAsset(ctx context.Context, id pgtype.UUID) (Asset, error)
	ListAssetsByOwner(ctx context.Context, arg ListAssetsByOwnerParams) ([]Asset, error)
	MarkAssetFailed(ctx context.Context, arg MarkAssetFailedParams) error
	MarkAssetProcessing(ctx context.Context, id pgtype.UUID) error
	MarkAssetReady(ctx context.Context, arg MarkAssetReadyParams) error
}

var _ Querier = (*Queries)(nil)
