// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mediarepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// id is generated by the app (so the source_key can embed it before insert).
	// title/original_filename are recorded at session start (SPEC-01 §6); origin is
	// 'upload' for the browser flow, 'import' for the SPEC-02 batch-create.
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	DeleteAsset(ctx context.Context, id pgtype.UUID) error
	// FK ON DELETE CASCADE already drops rows when the asset row goes, but the
	// purge path deletes storage objects first (enumerated via ListVariantsByAsset)
	// and this makes the row cleanup explicit / order-independent.
	DeleteVariantsByAsset(ctx context.Context, assetID pgtype.UUID) error
	GetAsset(ctx context.Context, id pgtype.UUID) (Asset, error)
	// Cheap owner lookup for the RequireOwnerOrPermission extractor (P0.3).
	GetAssetOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetContinueItems(ctx context.Context, arg GetContinueItemsParams) ([]GetContinueItemsRow, error)
	GetPlaybackProgress(ctx context.Context, arg GetPlaybackProgressParams) (GetPlaybackProgressRow, error)
	GetVariant(ctx context.Context, arg GetVariantParams) (MediaAssetVariant, error)
	// Derived, metadata-stripped variants (thumb/medium for images, poster for
	// video). The uploaded original is NEVER re-encoded — it stays as the asset's
	// own storage object; this table holds only derived artifacts (SPEC-01 §6).
	// Upsert so a re-run of the worker (retry / re-process) replaces the row and its
	// storage key instead of colliding on the (asset_id, variant) unique constraint.
	InsertVariant(ctx context.Context, arg InsertVariantParams) (MediaAssetVariant, error)
	// P0.3 janitor: upload sessions the browser never completed (>24h).
	ListAbandonedUploads(ctx context.Context) ([]Asset, error)
	ListAssetsByOwner(ctx context.Context, arg ListAssetsByOwnerParams) ([]Asset, error)
	// Library keyset page (P0.4). Excludes 'deleting' tombstones. Optional kind and
	// status filters; the status filter is a set so "processing" can also match
	// still-'uploading' sessions (rev 3). Keyset on (created_at, id) DESC, backed by
	// assets_owner_cursor_idx.
	ListAssetsByOwnerCursor(ctx context.Context, arg ListAssetsByOwnerCursorParams) ([]Asset, error)
	// P0.3 janitor: 'deleting' rows past the 15-min grace window (assets_deleting_idx).
	ListAssetsForPurge(ctx context.Context) ([]Asset, error)
	ListVariantsByAsset(ctx context.Context, assetID pgtype.UUID) ([]MediaAssetVariant, error)
	MarkAssetFailed(ctx context.Context, arg MarkAssetFailedParams) error
	// Image ready: sets dimensions but no output_prefix (images have no HLS output).
	MarkAssetImageReady(ctx context.Context, arg MarkAssetImageReadyParams) error
	MarkAssetProcessing(ctx context.Context, id pgtype.UUID) error
	MarkAssetReady(ctx context.Context, arg MarkAssetReadyParams) error
	// P0.3 soft-delete tombstone: excluded from listings until the purge removes it.
	SetAssetStatusDeleting(ctx context.Context, id pgtype.UUID) error
	UpsertPlaybackProgress(ctx context.Context, arg UpsertPlaybackProgressParams) error
}

var _ Querier = (*Queries)(nil)
