// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package opsrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Close a run as failed with a human-readable reason. The next night's run is
	// unaffected — a failed row is terminal, never a wedged 'running' (P0.2 AC).
	FinishBackupRunFailed(ctx context.Context, arg FinishBackupRunFailedParams) error
	// Close a run as succeeded: stamp finished_at, size, and the storage key of the
	// dump. Only ever applied to the run's own 'running' row.
	FinishBackupRunOK(ctx context.Context, arg FinishBackupRunOKParams) error
	// The most recent COMPLETED run (ok or failed; a still-'running' row is not
	// completed). Its status decides the `failed` precedence branch of the sentinel.
	GetLastCompletedRun(ctx context.Context) (OpsBackupRun, error)
	// The most recently started run of any status — the `last_run` block on
	// /ops/status (P0.5).
	GetLastRun(ctx context.Context) (OpsBackupRun, error)
	// The most recent succeeded run — drives last_success_at / hours_since_success.
	GetLastSuccessfulRun(ctx context.Context) (OpsBackupRun, error)
	// ops module queries (SPEC-09 P0). sqlc input only — regenerate with `make sqlc`;
	// never hand-edit the *.sql.go output. ops_backup_runs is system-scoped (no
	// user_id): backups are a platform concern, one ledger for the whole install.
	// Open a run in the 'running' state at the start of the nightly backup task. The
	// returned id threads through the finish/emit steps.
	InsertBackupRun(ctx context.Context) (pgtype.UUID, error)
	// Every succeeded run's storage key + completion time, newest first — the
	// candidate set the retention keep/prune pass runs over (P0.2 step 5).
	ListSuccessfulRuns(ctx context.Context) ([]ListSuccessfulRunsRow, error)
}

var _ Querier = (*Queries)(nil)
